/**
 * Generates the database twin of exercise-classifier.ts.
 *
 * The rules live once, as data, in exercise-classifier.ts. This module turns
 * them into `public.exercise_classify(name, category)` so every insert path
 * (library form, bulk import, quick swap, SQL) tags a new exercise exactly the
 * way the app classifies it. src/test/exercise-classifier-sql.test.ts fails if
 * the newest migration defining the function drifts from these rules: after
 * changing a rule, paste `exerciseClassifierSql()` into a new migration.
 */
import {
  COARSE_PATTERN,
  EQUIPMENT_RULES,
  NON_VOLUME_PATTERNS,
  REFINEMENTS,
  RULES,
  type Match,
  type MovementPattern,
} from "@/lib/exercise-classifier";

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;

const regex = (r: RegExp) => {
  // JS and Postgres (ARE) regexes agree on everything the rules use: literals,
  // alternation, groups, `?`, character classes. Escapes and flags differ
  // (e.g. \b), so refuse them rather than silently diverge.
  if (r.flags) throw new Error(`exercise rule regex must have no flags: ${r}`);
  if (r.source.includes("\\")) throw new Error(`exercise rule regex must not use escapes: ${r}`);
  return lit(r.source);
};

const cond = (m: Match) =>
  m instanceof RegExp
    ? `n ~ ${regex(m)}`
    : [
        `n ~ ${regex(m.re)}`,
        m.and ? `n ~ ${regex(m.and)}` : null,
        m.not ? `n !~ ${regex(m.not)}` : null,
      ]
        .filter(Boolean)
        .join(" AND ");

const arr = (xs: readonly string[]) =>
  xs.length ? `ARRAY[${xs.map(lit).join(", ")}]::text[]` : `'{}'::text[]`;

export function exerciseClassifierSql(): string {
  const equipment = EQUIPMENT_RULES.map(
    (r) => `      WHEN ${cond(r.match)} THEN ${lit(r.equipment)}`,
  ).join("\n");
  const rules = RULES.map(
    (r, i) =>
      `  ${i === 0 ? "IF" : "ELSIF"} ${cond(r.match)} THEN\n` +
      `    p := ${lit(r.pattern)}; pm := ${arr(r.primary)}; sm := ${arr(r.secondary)};`,
  ).join("\n");
  const refinements = REFINEMENTS.map(
    (r, i) =>
      `  ${i === 0 ? "IF" : "ELSIF"} p = ${lit(r.pattern)} AND ${cond(r.match)} THEN\n` +
      `    ${[
        r.primary ? `pm := ${arr(r.primary)};` : null,
        r.secondary ? `sm := ${arr(r.secondary)};` : null,
      ]
        .filter(Boolean)
        .join(" ")}`,
  ).join("\n");
  const coarse = (Object.entries(COARSE_PATTERN) as [MovementPattern, string][])
    .map(([fine, db]) => `WHEN ${lit(fine)} THEN ${lit(db)}`)
    .join(" ");
  const nonVolume = NON_VOLUME_PATTERNS.map(lit).join(", ");

  return `-- GENERATED by exerciseClassifierSql() in src/lib/exercise-classifier-sql.ts — do not hand-edit.
CREATE OR REPLACE FUNCTION public.exercise_classify(_name text, _category text DEFAULT NULL)
 RETURNS TABLE(pattern text, primary_muscles text[], secondary_muscles text[], equipment text, matched boolean)
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $fn$
DECLARE
  n text := ' ' || btrim(regexp_replace(lower(coalesce(_name, '')), '[^a-z0-9]+', ' ', 'g')) || ' ';
  c text := lower(coalesce(_category, ''));
  p text;
  pm text[];
  sm text[];
  eq text;
BEGIN
  eq := CASE
${equipment}
    END;
${rules}
  ELSIF position('stretch' in c) > 0 OR c = 'yoga' THEN
    RETURN QUERY SELECT 'mobility'::text, ARRAY['other']::text[], '{}'::text[], NULL::text, true;
    RETURN;
  ELSE
    RETURN QUERY SELECT 'other'::text, ARRAY['other']::text[], '{}'::text[], eq, false;
    RETURN;
  END IF;
${refinements}
  END IF;
  sm := ARRAY(SELECT m FROM unnest(sm) WITH ORDINALITY AS u(m, o) WHERE m <> ALL (pm) ORDER BY o);
  IF p = 'mobility' AND eq IS DISTINCT FROM 'Bands' THEN eq := NULL; END IF;
  RETURN QUERY SELECT p, pm, sm, eq, true;
END
$fn$;

-- Fine pattern → the coarse vocabulary exercises.primary_movement_pattern allows.
CREATE OR REPLACE FUNCTION public.exercise_coarse_pattern(_pattern text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $fn$
  SELECT CASE _pattern ${coarse} ELSE NULL END
$fn$;

-- Patterns that never build muscle volume.
CREATE OR REPLACE FUNCTION public.exercise_pattern_counts_toward_volume(_pattern text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $fn$
  SELECT _pattern IS NULL OR _pattern NOT IN (${nonVolume})
$fn$;
`;
}
