import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { filterActiveCalendarItems, isInactivePrimaryDay } from "@/lib/active-calendar";
import { formatCompactWorkoutLabel } from "@/lib/workout-day-label";
import { dayScheduledDate } from "@/lib/workout-today";

const today = "2026-08-21";

const completedBlock = (id: string, order: number) => ({
  id,
  sort_order: order,
  status: "Completed",
  start_date: "2026-02-01",
  end_date: "2026-04-01",
});
const activeBlock = { id: "b5", sort_order: 5, status: "Active", start_date: "2026-08-01", end_date: "2026-09-30" };
const upcomingBlock = { id: "b6", sort_order: 6, status: "Draft", start_date: "2026-10-01", end_date: "2026-11-30" };

const item = (block: any, dayId: string, extra: any = {}) => ({
  block,
  week: { id: `${block.id}-w1`, week_index: 1, training_days: null },
  day: { id: dayId, day_index: 1, scheduled_date: "2026-08-24", ...extra },
  completion: null,
});

describe("active workout calendar scope", () => {
  it("completed old blocks do not appear in the active calendar dataset", () => {
    const items = [
      item(completedBlock("b1", 1), "d1"),
      item(completedBlock("b2", 2), "d2"),
      item(completedBlock("b3", 3), "d3"),
      item(completedBlock("b4", 4), "d4"),
      item(activeBlock, "d5"),
    ];
    const kept = filterActiveCalendarItems(items, today);
    expect(kept.map((i) => i.block.id)).toEqual(["b5"]);
  });

  it("active + upcoming blocks do appear", () => {
    const items = [item(activeBlock, "d5"), item(upcomingBlock, "d6"), item(completedBlock("b1", 1), "d1")];
    const kept = filterActiveCalendarItems(items, today);
    expect(kept.map((i) => i.block.id).sort()).toEqual(["b5", "b6"]);
  });

  it("completed workouts inside the active block stay on the calendar", () => {
    const done = item(activeBlock, "d7", { scheduled_date: "2026-08-05" });
    (done as any).completion = { id: "c1", completed_at: "2026-08-05T18:00:00Z" };
    expect(filterActiveCalendarItems([done], today)).toHaveLength(1);
  });

  it("archived / deleted primary days are excluded from active rendering", () => {
    expect(isInactivePrimaryDay({ id: "d", archived: true })).toBe(true);
    expect(isInactivePrimaryDay({ id: "d", deleted_at: "2026-08-19T00:00:00Z" })).toBe(true);
    expect(isInactivePrimaryDay({ id: "d", archived: false, deleted_at: null })).toBe(false);
  });

  it("getClientWorkouts filters archived/deleted days before cadence fallback", () => {
    const src = readFileSync("src/lib/pl-programs.ts", "utf8");
    expect(src).toContain("const activeDays = (days ?? []).filter((day: any) => !isInactivePrimaryDay(day));");
  });

  it("an archived day with no scheduled instance cannot be regenerated by cadence fallback", () => {
    const archivedDay = { id: "stale", day_index: 4, scheduled_date: null, archived: true };
    const rows = [archivedDay, { id: "live", day_index: 1, scheduled_date: null, archived: false }];
    const active = rows.filter((d) => !isInactivePrimaryDay(d));
    expect(active.map((d) => d.id)).toEqual(["live"]);
    // The stale row never reaches the cadence-derivation helper at all.
    expect(active.find((d) => d.id === "stale")).toBeUndefined();
  });

  it("month labels distinguish W1 D3 from W2 D3", () => {
    const w1 = formatCompactWorkoutLabel({ day_index: 3, title: "Day 3", subtitle: null }, { week_index: 1 });
    const w2 = formatCompactWorkoutLabel({ day_index: 3, title: "Day 3", subtitle: null }, { week_index: 2 });
    expect(w1).toBe("W1 D3");
    expect(w2).toBe("W2 D3");
    expect(w1).not.toBe(w2);
  });

  it("meaningful subtitles remain meaningful labels", () => {
    expect(formatCompactWorkoutLabel({ day_index: 1, subtitle: "Primary SBD" }, { week_index: 2 })).toBe("Primary SBD");
    expect(formatCompactWorkoutLabel({ day_index: 2, subtitle: "Heavy Exposure" }, { week_index: 3 })).toBe("Heavy Exposure");
    expect(formatCompactWorkoutLabel({ day_index: 1, subtitle: "Primer Last Light Session" }, { week_index: 4 }))
      .toMatch(/^Primer Last Light/);
  });

  it("canonical instance date still beats derived cadence", () => {
    const d = dayScheduledDate(
      {
        day: { id: "d1", day_index: 1, scheduled_date: "2026-08-05" },
        week: { id: "w1", week_index: 1, training_days: null },
        block: { id: "b5", start_date: "2026-08-03" },
        completion: null,
        scheduledDate: "2026-08-11",
      } as any,
      ["monday", "wednesday", "friday"],
    );
    expect(d && `${d.getFullYear()}-08-11`).toBe("2026-08-11");
  });
});
