import { useQuery,useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const blank:any={id:"",client_id:"",athlete_name:"",sex:"male",status:"active",openpowerlifting_url:"",country_filter:"",jf_start_date:"",jf_end_date:"",tracking_notes:"",admin_notes:"",auto_sync:false};
export function PowerliftingAthleteProfiles({clients=[]}:{clients:any[]}){
 const qc=useQueryClient(); const [p,setP]=useState<any>(blank); const [period,setPeriod]=useState<any>({start_date:"",end_date:"",notes:""});
 const {data:athletes=[]}=useQuery({queryKey:["powerlifting-athletes-admin"],queryFn:async()=>{const {data,error}=await (supabase as any).from("powerlifting_athletes").select("*").order("athlete_name");if(error)throw error;return data??[]}});
 const {data:periods=[]}=useQuery({queryKey:["powerlifting-periods-admin",p.id],enabled:!!p.id,queryFn:async()=>{const {data,error}=await (supabase as any).from("powerlifting_coaching_periods").select("*").eq("athlete_id",p.id).order("start_date");if(error)throw error;return data??[]}});
 const save=async()=>{if(!p.athlete_name)return toast.error("Athlete name is required");const payload={...p,id:p.id||undefined,client_id:p.client_id||null,jf_start_date:p.jf_start_date||null,jf_end_date:p.jf_end_date||null,country_filter:p.country_filter||null,last_reviewed_at:new Date().toISOString()};const {data,error}=await (supabase as any).from("powerlifting_athletes").upsert(payload).select().single();if(error)return toast.error(error.message);toast.success("Athlete tracking profile saved");setP({...data});qc.invalidateQueries({queryKey:["powerlifting-athletes-admin"]});qc.invalidateQueries({queryKey:["powerlifting-athlete-roster"]})};
 const addPeriod=async()=>{if(!p.id)return toast.error("Save the athlete first");const {error}=await (supabase as any).from("powerlifting_coaching_periods").insert({athlete_id:p.id,start_date:period.start_date||null,end_date:period.end_date||null,notes:period.notes||null});if(error)return toast.error(error.message);setPeriod({start_date:"",end_date:"",notes:""});toast.success("Coaching period added");qc.invalidateQueries({queryKey:["powerlifting-periods-admin",p.id]})};
 const delPeriod=async(id:string)=>{const {error}=await (supabase as any).from("powerlifting_coaching_periods").delete().eq("id",id);if(error)return toast.error(error.message);qc.invalidateQueries({queryKey:["powerlifting-periods-admin",p.id]})};
 const edit=(a:any)=>setP({...blank,...a,jf_start_date:a.jf_start_date||"",jf_end_date:a.jf_end_date||"",openpowerlifting_url:a.openpowerlifting_url||"",country_filter:a.country_filter||"",tracking_notes:a.tracking_notes||"",admin_notes:a.admin_notes||""});
 return <Card className="p-4"><div className="mb-4"><div className="font-black">JF Powerlifting Athlete Database</div><div className="text-xs text-muted-foreground">Permanent source of truth for active, retired and returning athletes. Tracking rules determine which meets belong to JF records.</div></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
 <F l="Linked client"><Select value={p.client_id||"none"} onValueChange={v=>{const c=clients.find(x=>x.id===v);setP({...p,client_id:v==="none"?"":v,athlete_name:c?.full_name||p.athlete_name})}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Historical / retired</SelectItem>{clients.map(c=><SelectItem key={c.id} value={c.id}>{c.full_name}</SelectItem>)}</SelectContent></Select></F>
 <F l="Athlete name"><Input value={p.athlete_name} onChange={e=>setP({...p,athlete_name:e.target.value})}/></F>
 <F l="Sex"><Select value={p.sex} onValueChange={v=>setP({...p,sex:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="male">Male</SelectItem><SelectItem value="female">Female</SelectItem></SelectContent></Select></F>
 <F l="Status"><Select value={p.status||"active"} onValueChange={v=>setP({...p,status:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="retired">Retired</SelectItem><SelectItem value="paused">Paused</SelectItem></SelectContent></Select></F>
 <F l="OpenPowerlifting URL"><Input value={p.openpowerlifting_url||""} onChange={e=>setP({...p,openpowerlifting_url:e.target.value})} placeholder="https://openpowerlifting.org/u/..."/></F>
 <F l="Country restriction"><Input value={p.country_filter||""} onChange={e=>setP({...p,country_filter:e.target.value})} placeholder="e.g. Canada only"/></F>
 </div>
 <div className="mt-3 grid gap-3 sm:grid-cols-2"><F l="Tracking rules / eligibility notes"><Textarea className="min-h-24" value={p.tracking_notes||""} onChange={e=>setP({...p,tracking_notes:e.target.value})} placeholder="Example: only 2024 Canadian meets count; retired after Dec 14, 2024; exclude USA namesake."/></F><F l="Private coach/admin notes"><Textarea className="min-h-24" value={p.admin_notes||""} onChange={e=>setP({...p,admin_notes:e.target.value})} placeholder="Anything coaches should remember when reviewing or updating this athlete."/></F></div>
 <Button className="mt-4" onClick={save}>Save athlete profile</Button>
 {p.id&&<div className="mt-5 rounded-xl border p-3"><div className="font-bold">JF coaching periods</div><div className="mb-3 text-xs text-muted-foreground">Add another period if an athlete returns from retirement. Only meets inside at least one period count.</div>
 <div className="grid gap-2 sm:grid-cols-3"><F l="Start"><Input type="date" value={period.start_date} onChange={e=>setPeriod({...period,start_date:e.target.value})}/></F><F l="End"><Input type="date" value={period.end_date} onChange={e=>setPeriod({...period,end_date:e.target.value})}/></F><F l="Period note"><Input value={period.notes} onChange={e=>setPeriod({...period,notes:e.target.value})} placeholder="Why this period counts"/></F></div><Button variant="outline" className="mt-2" onClick={addPeriod}>Add coaching period</Button>
 <div className="mt-3 divide-y">{periods.map((x:any)=><div key={x.id} className="flex items-start justify-between py-2 text-xs"><div><b>{x.start_date||"Career start"} → {x.end_date||"Current"}</b><div className="text-muted-foreground">{x.notes||"JF coached period"}</div></div><Button variant="ghost" size="sm" onClick={()=>delPeriod(x.id)}>Remove</Button></div>)}</div></div>}
 <div className="mt-4 divide-y rounded-xl border">{athletes.map((a:any)=><button type="button" key={a.id} onClick={()=>edit(a)} className="flex w-full items-center justify-between gap-3 p-3 text-left"><span className="min-w-0"><b className="block truncate text-sm">{a.athlete_name}</b><span className="text-[11px] text-muted-foreground">{a.status||"active"} · {a.openpowerlifting_url?"OPL linked":"manual tracking"}{a.country_filter?` · ${a.country_filter}`:""}</span></span><span className="text-xs text-primary">Manage</span></button>)}</div></Card>
}
function F({l,children}:{l:string;children:any}){return <div className="space-y-1.5"><Label className="text-xs">{l}</Label>{children}</div>}
