/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPortalResourcesRouteImport } from './routes/_authenticated/portal/resources'
import { Route as AuthenticatedPortalProgramRouteImport } from './routes/_authenticated/portal/program'
import { Route as AuthenticatedPortalPaymentsRouteImport } from './routes/_authenticated/portal/payments'
import { Route as AuthenticatedPortalExercisesRouteImport } from './routes/_authenticated/portal/exercises'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedPortalCheckInRouteImport } from './routes/_authenticated/portal/check-in'
import { Route as AuthenticatedPortalCalendarRouteImport } from './routes/_authenticated/portal/calendar'
import { Route as AuthenticatedAdminTrainingPhasesRouteImport } from './routes/_authenticated/admin/training-phases'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminSopsRouteImport } from './routes/_authenticated/admin/sops'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminSalesCallsRouteImport } from './routes/_authenticated/admin/sales-calls'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin/programs'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin/offers'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminExercisesRouteImport } from './routes/_authenticated/admin/exercises'
import { Route as AuthenticatedAdminContentIdeasRouteImport } from './routes/_authenticated/admin/content-ideas'
import { Route as AuthenticatedAdminCheckInsRouteImport } from './routes/_authenticated/admin/check-ins'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin/calendar'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin/automations'
import { Route as AuthenticatedAdminAppsRouteImport } from './routes/_authenticated/admin/apps'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin/clients.index'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin/clients.$id'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPortalResourcesRoute =
  AuthenticatedPortalResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalProgramRoute =
  AuthenticatedPortalProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPaymentsRoute =
  AuthenticatedPortalPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalExercisesRoute =
  AuthenticatedPortalExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCheckInRoute =
  AuthenticatedPortalCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCalendarRoute =
  AuthenticatedPortalCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminTrainingPhasesRoute =
  AuthenticatedAdminTrainingPhasesRouteImport.update({
    id: '/training-phases',
    path: '/training-phases',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSopsRoute = AuthenticatedAdminSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSalesCallsRoute =
  AuthenticatedAdminSalesCallsRouteImport.update({
    id: '/sales-calls',
    path: '/sales-calls',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminExercisesRoute =
  AuthenticatedAdminExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentIdeasRoute =
  AuthenticatedAdminContentIdeasRouteImport.update({
    id: '/content-ideas',
    path: '/content-ideas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCheckInsRoute =
  AuthenticatedAdminCheckInsRouteImport.update({
    id: '/check-ins',
    path: '/check-ins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAppsRoute = AuthenticatedAdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap': typeof SitemapRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/check-ins': typeof AuthenticatedAdminCheckInsRoute
  '/admin/content-ideas': typeof AuthenticatedAdminContentIdeasRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/sales-calls': typeof AuthenticatedAdminSalesCallsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sops': typeof AuthenticatedAdminSopsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/training-phases': typeof AuthenticatedAdminTrainingPhasesRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/check-in': typeof AuthenticatedPortalCheckInRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/exercises': typeof AuthenticatedPortalExercisesRoute
  '/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/portal/program': typeof AuthenticatedPortalProgramRoute
  '/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap': typeof SitemapRoute
  '/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/check-ins': typeof AuthenticatedAdminCheckInsRoute
  '/admin/content-ideas': typeof AuthenticatedAdminContentIdeasRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/sales-calls': typeof AuthenticatedAdminSalesCallsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sops': typeof AuthenticatedAdminSopsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/training-phases': typeof AuthenticatedAdminTrainingPhasesRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/check-in': typeof AuthenticatedPortalCheckInRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/exercises': typeof AuthenticatedPortalExercisesRoute
  '/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/portal/program': typeof AuthenticatedPortalProgramRoute
  '/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap': typeof SitemapRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/check-ins': typeof AuthenticatedAdminCheckInsRoute
  '/_authenticated/admin/content-ideas': typeof AuthenticatedAdminContentIdeasRoute
  '/_authenticated/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/sales-calls': typeof AuthenticatedAdminSalesCallsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sops': typeof AuthenticatedAdminSopsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/training-phases': typeof AuthenticatedAdminTrainingPhasesRoute
  '/_authenticated/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/_authenticated/portal/check-in': typeof AuthenticatedPortalCheckInRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/exercises': typeof AuthenticatedPortalExercisesRoute
  '/_authenticated/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/_authenticated/portal/program': typeof AuthenticatedPortalProgramRoute
  '/_authenticated/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/sitemap'
    | '/admin'
    | '/portal'
    | '/admin/apps'
    | '/admin/automations'
    | '/admin/calendar'
    | '/admin/check-ins'
    | '/admin/content-ideas'
    | '/admin/exercises'
    | '/admin/leads'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/programs'
    | '/admin/resources'
    | '/admin/sales-calls'
    | '/admin/settings'
    | '/admin/sops'
    | '/admin/testimonials'
    | '/admin/training-phases'
    | '/portal/calendar'
    | '/portal/check-in'
    | '/portal/documents'
    | '/portal/exercises'
    | '/portal/payments'
    | '/portal/program'
    | '/portal/resources'
    | '/admin/'
    | '/portal/'
    | '/admin/clients/$id'
    | '/admin/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/sitemap'
    | '/admin/apps'
    | '/admin/automations'
    | '/admin/calendar'
    | '/admin/check-ins'
    | '/admin/content-ideas'
    | '/admin/exercises'
    | '/admin/leads'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/programs'
    | '/admin/resources'
    | '/admin/sales-calls'
    | '/admin/settings'
    | '/admin/sops'
    | '/admin/testimonials'
    | '/admin/training-phases'
    | '/portal/calendar'
    | '/portal/check-in'
    | '/portal/documents'
    | '/portal/exercises'
    | '/portal/payments'
    | '/portal/program'
    | '/portal/resources'
    | '/admin'
    | '/portal'
    | '/admin/clients/$id'
    | '/admin/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/sitemap'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/admin/apps'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/check-ins'
    | '/_authenticated/admin/content-ideas'
    | '/_authenticated/admin/exercises'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/sales-calls'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sops'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/training-phases'
    | '/_authenticated/portal/calendar'
    | '/_authenticated/portal/check-in'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/exercises'
    | '/_authenticated/portal/payments'
    | '/_authenticated/portal/program'
    | '/_authenticated/portal/resources'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SitemapRoute: typeof SitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portal/resources': {
      id: '/_authenticated/portal/resources'
      path: '/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof AuthenticatedPortalResourcesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/program': {
      id: '/_authenticated/portal/program'
      path: '/program'
      fullPath: '/portal/program'
      preLoaderRoute: typeof AuthenticatedPortalProgramRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/payments': {
      id: '/_authenticated/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof AuthenticatedPortalPaymentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/exercises': {
      id: '/_authenticated/portal/exercises'
      path: '/exercises'
      fullPath: '/portal/exercises'
      preLoaderRoute: typeof AuthenticatedPortalExercisesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/check-in': {
      id: '/_authenticated/portal/check-in'
      path: '/check-in'
      fullPath: '/portal/check-in'
      preLoaderRoute: typeof AuthenticatedPortalCheckInRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/calendar': {
      id: '/_authenticated/portal/calendar'
      path: '/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof AuthenticatedPortalCalendarRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/training-phases': {
      id: '/_authenticated/admin/training-phases'
      path: '/training-phases'
      fullPath: '/admin/training-phases'
      preLoaderRoute: typeof AuthenticatedAdminTrainingPhasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sops': {
      id: '/_authenticated/admin/sops'
      path: '/sops'
      fullPath: '/admin/sops'
      preLoaderRoute: typeof AuthenticatedAdminSopsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sales-calls': {
      id: '/_authenticated/admin/sales-calls'
      path: '/sales-calls'
      fullPath: '/admin/sales-calls'
      preLoaderRoute: typeof AuthenticatedAdminSalesCallsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exercises': {
      id: '/_authenticated/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AuthenticatedAdminExercisesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content-ideas': {
      id: '/_authenticated/admin/content-ideas'
      path: '/content-ideas'
      fullPath: '/admin/content-ideas'
      preLoaderRoute: typeof AuthenticatedAdminContentIdeasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/check-ins': {
      id: '/_authenticated/admin/check-ins'
      path: '/check-ins'
      fullPath: '/admin/check-ins'
      preLoaderRoute: typeof AuthenticatedAdminCheckInsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/apps': {
      id: '/_authenticated/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AuthenticatedAdminAppsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAppsRoute: typeof AuthenticatedAdminAppsRoute
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminCheckInsRoute: typeof AuthenticatedAdminCheckInsRoute
  AuthenticatedAdminContentIdeasRoute: typeof AuthenticatedAdminContentIdeasRoute
  AuthenticatedAdminExercisesRoute: typeof AuthenticatedAdminExercisesRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSalesCallsRoute: typeof AuthenticatedAdminSalesCallsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSopsRoute: typeof AuthenticatedAdminSopsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTrainingPhasesRoute: typeof AuthenticatedAdminTrainingPhasesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAppsRoute: AuthenticatedAdminAppsRoute,
    AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
    AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
    AuthenticatedAdminCheckInsRoute: AuthenticatedAdminCheckInsRoute,
    AuthenticatedAdminContentIdeasRoute: AuthenticatedAdminContentIdeasRoute,
    AuthenticatedAdminExercisesRoute: AuthenticatedAdminExercisesRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
    AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
    AuthenticatedAdminSalesCallsRoute: AuthenticatedAdminSalesCallsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSopsRoute: AuthenticatedAdminSopsRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminTrainingPhasesRoute:
      AuthenticatedAdminTrainingPhasesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalCalendarRoute: typeof AuthenticatedPortalCalendarRoute
  AuthenticatedPortalCheckInRoute: typeof AuthenticatedPortalCheckInRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalExercisesRoute: typeof AuthenticatedPortalExercisesRoute
  AuthenticatedPortalPaymentsRoute: typeof AuthenticatedPortalPaymentsRoute
  AuthenticatedPortalProgramRoute: typeof AuthenticatedPortalProgramRoute
  AuthenticatedPortalResourcesRoute: typeof AuthenticatedPortalResourcesRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalCalendarRoute: AuthenticatedPortalCalendarRoute,
    AuthenticatedPortalCheckInRoute: AuthenticatedPortalCheckInRoute,
    AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
    AuthenticatedPortalExercisesRoute: AuthenticatedPortalExercisesRoute,
    AuthenticatedPortalPaymentsRoute: AuthenticatedPortalPaymentsRoute,
    AuthenticatedPortalProgramRoute: AuthenticatedPortalProgramRoute,
    AuthenticatedPortalResourcesRoute: AuthenticatedPortalResourcesRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SitemapRoute: SitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
