/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicSignnowWebhookRouteImport } from './routes/api/public/signnow-webhook'
import { Route as AuthenticatedPortalResourcesRouteImport } from './routes/_authenticated/portal/resources'
import { Route as AuthenticatedPortalPurchasesRouteImport } from './routes/_authenticated/portal/purchases'
import { Route as AuthenticatedPortalProgramRouteImport } from './routes/_authenticated/portal/program'
import { Route as AuthenticatedPortalPaymentsRouteImport } from './routes/_authenticated/portal/payments'
import { Route as AuthenticatedPortalNutritionTargetsRouteImport } from './routes/_authenticated/portal/nutrition-targets'
import { Route as AuthenticatedPortalMessagesRouteImport } from './routes/_authenticated/portal/messages'
import { Route as AuthenticatedPortalMediaRouteImport } from './routes/_authenticated/portal/media'
import { Route as AuthenticatedPortalLiftVideosRouteImport } from './routes/_authenticated/portal/lift-videos'
import { Route as AuthenticatedPortalExercisesRouteImport } from './routes/_authenticated/portal/exercises'
import { Route as AuthenticatedPortalDocumentsRouteImport } from './routes/_authenticated/portal/documents'
import { Route as AuthenticatedPortalCheckInRouteImport } from './routes/_authenticated/portal/check-in'
import { Route as AuthenticatedPortalCalendarRouteImport } from './routes/_authenticated/portal/calendar'
import { Route as AuthenticatedPortalAccountRouteImport } from './routes/_authenticated/portal/account'
import { Route as AuthenticatedAdminTrainingPhasesRouteImport } from './routes/_authenticated/admin/training-phases'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminSopsRouteImport } from './routes/_authenticated/admin/sops'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as AuthenticatedAdminPurchasesRouteImport } from './routes/_authenticated/admin/purchases'
import { Route as AuthenticatedAdminProgramsRouteImport } from './routes/_authenticated/admin/programs'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin/offers'
import { Route as AuthenticatedAdminNutritionTargetsRouteImport } from './routes/_authenticated/admin/nutrition-targets'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminMediaReviewRouteImport } from './routes/_authenticated/admin/media-review'
import { Route as AuthenticatedAdminLiftVideosRouteImport } from './routes/_authenticated/admin/lift-videos'
import { Route as AuthenticatedAdminExercisesRouteImport } from './routes/_authenticated/admin/exercises'
import { Route as AuthenticatedAdminContentIdeasRouteImport } from './routes/_authenticated/admin/content-ideas'
import { Route as AuthenticatedAdminCheckInsRouteImport } from './routes/_authenticated/admin/check-ins'
import { Route as AuthenticatedAdminCardioTargetsRouteImport } from './routes/_authenticated/admin/cardio-targets'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin/calendar'
import { Route as AuthenticatedAdminBusinessSystemsRouteImport } from './routes/_authenticated/admin/business-systems'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin/automations'
import { Route as AuthenticatedAdminAppsRouteImport } from './routes/_authenticated/admin/apps'
import { Route as AuthenticatedPortalAgreementsIndexRouteImport } from './routes/_authenticated/portal/agreements.index'
import { Route as AuthenticatedAdminCoachesIndexRouteImport } from './routes/_authenticated/admin/coaches.index'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin/clients.index'
import { Route as AuthenticatedAdminAgreementsIndexRouteImport } from './routes/_authenticated/admin/agreements.index'
import { Route as AuthenticatedPortalPurchasesIdRouteImport } from './routes/_authenticated/portal/purchases.$id'
import { Route as AuthenticatedAdminPurchasesIdRouteImport } from './routes/_authenticated/admin/purchases.$id'
import { Route as AuthenticatedAdminCoachesIdRouteImport } from './routes/_authenticated/admin/coaches.$id'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin/clients.$id'
import { Route as AuthenticatedAdminAgreementsSignedRouteImport } from './routes/_authenticated/admin/agreements.signed'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const ApiPublicSignnowWebhookRoute = ApiPublicSignnowWebhookRouteImport.update({
  id: '/api/public/signnow-webhook',
  path: '/api/public/signnow-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalResourcesRoute =
  AuthenticatedPortalResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPurchasesRoute =
  AuthenticatedPortalPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalProgramRoute =
  AuthenticatedPortalProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPaymentsRoute =
  AuthenticatedPortalPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalNutritionTargetsRoute =
  AuthenticatedPortalNutritionTargetsRouteImport.update({
    id: '/nutrition-targets',
    path: '/nutrition-targets',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMessagesRoute =
  AuthenticatedPortalMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMediaRoute =
  AuthenticatedPortalMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalLiftVideosRoute =
  AuthenticatedPortalLiftVideosRouteImport.update({
    id: '/lift-videos',
    path: '/lift-videos',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalExercisesRoute =
  AuthenticatedPortalExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalDocumentsRoute =
  AuthenticatedPortalDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCheckInRoute =
  AuthenticatedPortalCheckInRouteImport.update({
    id: '/check-in',
    path: '/check-in',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCalendarRoute =
  AuthenticatedPortalCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalAccountRoute =
  AuthenticatedPortalAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminTrainingPhasesRoute =
  AuthenticatedAdminTrainingPhasesRouteImport.update({
    id: '/training-phases',
    path: '/training-phases',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSopsRoute = AuthenticatedAdminSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPurchasesRoute =
  AuthenticatedAdminPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProgramsRoute =
  AuthenticatedAdminProgramsRouteImport.update({
    id: '/programs',
    path: '/programs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNutritionTargetsRoute =
  AuthenticatedAdminNutritionTargetsRouteImport.update({
    id: '/nutrition-targets',
    path: '/nutrition-targets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaReviewRoute =
  AuthenticatedAdminMediaReviewRouteImport.update({
    id: '/media-review',
    path: '/media-review',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLiftVideosRoute =
  AuthenticatedAdminLiftVideosRouteImport.update({
    id: '/lift-videos',
    path: '/lift-videos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExercisesRoute =
  AuthenticatedAdminExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentIdeasRoute =
  AuthenticatedAdminContentIdeasRouteImport.update({
    id: '/content-ideas',
    path: '/content-ideas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCheckInsRoute =
  AuthenticatedAdminCheckInsRouteImport.update({
    id: '/check-ins',
    path: '/check-ins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCardioTargetsRoute =
  AuthenticatedAdminCardioTargetsRouteImport.update({
    id: '/cardio-targets',
    path: '/cardio-targets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBusinessSystemsRoute =
  AuthenticatedAdminBusinessSystemsRouteImport.update({
    id: '/business-systems',
    path: '/business-systems',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAppsRoute = AuthenticatedAdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPortalAgreementsIndexRoute =
  AuthenticatedPortalAgreementsIndexRouteImport.update({
    id: '/agreements/',
    path: '/agreements/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedAdminCoachesIndexRoute =
  AuthenticatedAdminCoachesIndexRouteImport.update({
    id: '/coaches/',
    path: '/coaches/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAgreementsIndexRoute =
  AuthenticatedAdminAgreementsIndexRouteImport.update({
    id: '/agreements/',
    path: '/agreements/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedPortalPurchasesIdRoute =
  AuthenticatedPortalPurchasesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalPurchasesRoute,
  } as any)
const AuthenticatedAdminPurchasesIdRoute =
  AuthenticatedAdminPurchasesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPurchasesRoute,
  } as any)
const AuthenticatedAdminCoachesIdRoute =
  AuthenticatedAdminCoachesIdRouteImport.update({
    id: '/coaches/$id',
    path: '/coaches/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/clients/$id',
    path: '/clients/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAgreementsSignedRoute =
  AuthenticatedAdminAgreementsSignedRouteImport.update({
    id: '/agreements/signed',
    path: '/agreements/signed',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap': typeof SitemapRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/business-systems': typeof AuthenticatedAdminBusinessSystemsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/cardio-targets': typeof AuthenticatedAdminCardioTargetsRoute
  '/admin/check-ins': typeof AuthenticatedAdminCheckInsRoute
  '/admin/content-ideas': typeof AuthenticatedAdminContentIdeasRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/lift-videos': typeof AuthenticatedAdminLiftVideosRoute
  '/admin/media-review': typeof AuthenticatedAdminMediaReviewRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/nutrition-targets': typeof AuthenticatedAdminNutritionTargetsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRouteWithChildren
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sops': typeof AuthenticatedAdminSopsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/training-phases': typeof AuthenticatedAdminTrainingPhasesRoute
  '/portal/account': typeof AuthenticatedPortalAccountRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/check-in': typeof AuthenticatedPortalCheckInRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/exercises': typeof AuthenticatedPortalExercisesRoute
  '/portal/lift-videos': typeof AuthenticatedPortalLiftVideosRoute
  '/portal/media': typeof AuthenticatedPortalMediaRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/nutrition-targets': typeof AuthenticatedPortalNutritionTargetsRoute
  '/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/portal/program': typeof AuthenticatedPortalProgramRoute
  '/portal/purchases': typeof AuthenticatedPortalPurchasesRouteWithChildren
  '/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/api/public/signnow-webhook': typeof ApiPublicSignnowWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/admin/agreements/signed': typeof AuthenticatedAdminAgreementsSignedRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/coaches/$id': typeof AuthenticatedAdminCoachesIdRoute
  '/admin/purchases/$id': typeof AuthenticatedAdminPurchasesIdRoute
  '/portal/purchases/$id': typeof AuthenticatedPortalPurchasesIdRoute
  '/admin/agreements/': typeof AuthenticatedAdminAgreementsIndexRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/coaches/': typeof AuthenticatedAdminCoachesIndexRoute
  '/portal/agreements/': typeof AuthenticatedPortalAgreementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap': typeof SitemapRoute
  '/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/business-systems': typeof AuthenticatedAdminBusinessSystemsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/cardio-targets': typeof AuthenticatedAdminCardioTargetsRoute
  '/admin/check-ins': typeof AuthenticatedAdminCheckInsRoute
  '/admin/content-ideas': typeof AuthenticatedAdminContentIdeasRoute
  '/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/admin/lift-videos': typeof AuthenticatedAdminLiftVideosRoute
  '/admin/media-review': typeof AuthenticatedAdminMediaReviewRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/nutrition-targets': typeof AuthenticatedAdminNutritionTargetsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/admin/purchases': typeof AuthenticatedAdminPurchasesRouteWithChildren
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sops': typeof AuthenticatedAdminSopsRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/training-phases': typeof AuthenticatedAdminTrainingPhasesRoute
  '/portal/account': typeof AuthenticatedPortalAccountRoute
  '/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/portal/check-in': typeof AuthenticatedPortalCheckInRoute
  '/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/portal/exercises': typeof AuthenticatedPortalExercisesRoute
  '/portal/lift-videos': typeof AuthenticatedPortalLiftVideosRoute
  '/portal/media': typeof AuthenticatedPortalMediaRoute
  '/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/portal/nutrition-targets': typeof AuthenticatedPortalNutritionTargetsRoute
  '/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/portal/program': typeof AuthenticatedPortalProgramRoute
  '/portal/purchases': typeof AuthenticatedPortalPurchasesRouteWithChildren
  '/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/api/public/signnow-webhook': typeof ApiPublicSignnowWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/admin/agreements/signed': typeof AuthenticatedAdminAgreementsSignedRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/coaches/$id': typeof AuthenticatedAdminCoachesIdRoute
  '/admin/purchases/$id': typeof AuthenticatedAdminPurchasesIdRoute
  '/portal/purchases/$id': typeof AuthenticatedPortalPurchasesIdRoute
  '/admin/agreements': typeof AuthenticatedAdminAgreementsIndexRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/coaches': typeof AuthenticatedAdminCoachesIndexRoute
  '/portal/agreements': typeof AuthenticatedPortalAgreementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap': typeof SitemapRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/business-systems': typeof AuthenticatedAdminBusinessSystemsRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/cardio-targets': typeof AuthenticatedAdminCardioTargetsRoute
  '/_authenticated/admin/check-ins': typeof AuthenticatedAdminCheckInsRoute
  '/_authenticated/admin/content-ideas': typeof AuthenticatedAdminContentIdeasRoute
  '/_authenticated/admin/exercises': typeof AuthenticatedAdminExercisesRoute
  '/_authenticated/admin/lift-videos': typeof AuthenticatedAdminLiftVideosRoute
  '/_authenticated/admin/media-review': typeof AuthenticatedAdminMediaReviewRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/nutrition-targets': typeof AuthenticatedAdminNutritionTargetsRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/programs': typeof AuthenticatedAdminProgramsRoute
  '/_authenticated/admin/purchases': typeof AuthenticatedAdminPurchasesRouteWithChildren
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sops': typeof AuthenticatedAdminSopsRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/training-phases': typeof AuthenticatedAdminTrainingPhasesRoute
  '/_authenticated/portal/account': typeof AuthenticatedPortalAccountRoute
  '/_authenticated/portal/calendar': typeof AuthenticatedPortalCalendarRoute
  '/_authenticated/portal/check-in': typeof AuthenticatedPortalCheckInRoute
  '/_authenticated/portal/documents': typeof AuthenticatedPortalDocumentsRoute
  '/_authenticated/portal/exercises': typeof AuthenticatedPortalExercisesRoute
  '/_authenticated/portal/lift-videos': typeof AuthenticatedPortalLiftVideosRoute
  '/_authenticated/portal/media': typeof AuthenticatedPortalMediaRoute
  '/_authenticated/portal/messages': typeof AuthenticatedPortalMessagesRoute
  '/_authenticated/portal/nutrition-targets': typeof AuthenticatedPortalNutritionTargetsRoute
  '/_authenticated/portal/payments': typeof AuthenticatedPortalPaymentsRoute
  '/_authenticated/portal/program': typeof AuthenticatedPortalProgramRoute
  '/_authenticated/portal/purchases': typeof AuthenticatedPortalPurchasesRouteWithChildren
  '/_authenticated/portal/resources': typeof AuthenticatedPortalResourcesRoute
  '/api/public/signnow-webhook': typeof ApiPublicSignnowWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/admin/agreements/signed': typeof AuthenticatedAdminAgreementsSignedRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/coaches/$id': typeof AuthenticatedAdminCoachesIdRoute
  '/_authenticated/admin/purchases/$id': typeof AuthenticatedAdminPurchasesIdRoute
  '/_authenticated/portal/purchases/$id': typeof AuthenticatedPortalPurchasesIdRoute
  '/_authenticated/admin/agreements/': typeof AuthenticatedAdminAgreementsIndexRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/coaches/': typeof AuthenticatedAdminCoachesIndexRoute
  '/_authenticated/portal/agreements/': typeof AuthenticatedPortalAgreementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/sitemap'
    | '/admin'
    | '/portal'
    | '/admin/apps'
    | '/admin/automations'
    | '/admin/business-systems'
    | '/admin/calendar'
    | '/admin/cardio-targets'
    | '/admin/check-ins'
    | '/admin/content-ideas'
    | '/admin/exercises'
    | '/admin/lift-videos'
    | '/admin/media-review'
    | '/admin/messages'
    | '/admin/nutrition-targets'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/programs'
    | '/admin/purchases'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/sops'
    | '/admin/testimonials'
    | '/admin/training-phases'
    | '/portal/account'
    | '/portal/calendar'
    | '/portal/check-in'
    | '/portal/documents'
    | '/portal/exercises'
    | '/portal/lift-videos'
    | '/portal/media'
    | '/portal/messages'
    | '/portal/nutrition-targets'
    | '/portal/payments'
    | '/portal/program'
    | '/portal/purchases'
    | '/portal/resources'
    | '/api/public/signnow-webhook'
    | '/admin/'
    | '/portal/'
    | '/admin/agreements/signed'
    | '/admin/clients/$id'
    | '/admin/coaches/$id'
    | '/admin/purchases/$id'
    | '/portal/purchases/$id'
    | '/admin/agreements/'
    | '/admin/clients/'
    | '/admin/coaches/'
    | '/portal/agreements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/sitemap'
    | '/admin/apps'
    | '/admin/automations'
    | '/admin/business-systems'
    | '/admin/calendar'
    | '/admin/cardio-targets'
    | '/admin/check-ins'
    | '/admin/content-ideas'
    | '/admin/exercises'
    | '/admin/lift-videos'
    | '/admin/media-review'
    | '/admin/messages'
    | '/admin/nutrition-targets'
    | '/admin/offers'
    | '/admin/payments'
    | '/admin/programs'
    | '/admin/purchases'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/sops'
    | '/admin/testimonials'
    | '/admin/training-phases'
    | '/portal/account'
    | '/portal/calendar'
    | '/portal/check-in'
    | '/portal/documents'
    | '/portal/exercises'
    | '/portal/lift-videos'
    | '/portal/media'
    | '/portal/messages'
    | '/portal/nutrition-targets'
    | '/portal/payments'
    | '/portal/program'
    | '/portal/purchases'
    | '/portal/resources'
    | '/api/public/signnow-webhook'
    | '/admin'
    | '/portal'
    | '/admin/agreements/signed'
    | '/admin/clients/$id'
    | '/admin/coaches/$id'
    | '/admin/purchases/$id'
    | '/portal/purchases/$id'
    | '/admin/agreements'
    | '/admin/clients'
    | '/admin/coaches'
    | '/portal/agreements'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/setup'
    | '/sitemap'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/_authenticated/admin/apps'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/business-systems'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/cardio-targets'
    | '/_authenticated/admin/check-ins'
    | '/_authenticated/admin/content-ideas'
    | '/_authenticated/admin/exercises'
    | '/_authenticated/admin/lift-videos'
    | '/_authenticated/admin/media-review'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/nutrition-targets'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/programs'
    | '/_authenticated/admin/purchases'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sops'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/training-phases'
    | '/_authenticated/portal/account'
    | '/_authenticated/portal/calendar'
    | '/_authenticated/portal/check-in'
    | '/_authenticated/portal/documents'
    | '/_authenticated/portal/exercises'
    | '/_authenticated/portal/lift-videos'
    | '/_authenticated/portal/media'
    | '/_authenticated/portal/messages'
    | '/_authenticated/portal/nutrition-targets'
    | '/_authenticated/portal/payments'
    | '/_authenticated/portal/program'
    | '/_authenticated/portal/purchases'
    | '/_authenticated/portal/resources'
    | '/api/public/signnow-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
    | '/_authenticated/admin/agreements/signed'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/coaches/$id'
    | '/_authenticated/admin/purchases/$id'
    | '/_authenticated/portal/purchases/$id'
    | '/_authenticated/admin/agreements/'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/coaches/'
    | '/_authenticated/portal/agreements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SitemapRoute: typeof SitemapRoute
  ApiPublicSignnowWebhookRoute: typeof ApiPublicSignnowWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/signnow-webhook': {
      id: '/api/public/signnow-webhook'
      path: '/api/public/signnow-webhook'
      fullPath: '/api/public/signnow-webhook'
      preLoaderRoute: typeof ApiPublicSignnowWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/resources': {
      id: '/_authenticated/portal/resources'
      path: '/resources'
      fullPath: '/portal/resources'
      preLoaderRoute: typeof AuthenticatedPortalResourcesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/purchases': {
      id: '/_authenticated/portal/purchases'
      path: '/purchases'
      fullPath: '/portal/purchases'
      preLoaderRoute: typeof AuthenticatedPortalPurchasesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/program': {
      id: '/_authenticated/portal/program'
      path: '/program'
      fullPath: '/portal/program'
      preLoaderRoute: typeof AuthenticatedPortalProgramRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/payments': {
      id: '/_authenticated/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof AuthenticatedPortalPaymentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/nutrition-targets': {
      id: '/_authenticated/portal/nutrition-targets'
      path: '/nutrition-targets'
      fullPath: '/portal/nutrition-targets'
      preLoaderRoute: typeof AuthenticatedPortalNutritionTargetsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/messages': {
      id: '/_authenticated/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof AuthenticatedPortalMessagesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/media': {
      id: '/_authenticated/portal/media'
      path: '/media'
      fullPath: '/portal/media'
      preLoaderRoute: typeof AuthenticatedPortalMediaRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/lift-videos': {
      id: '/_authenticated/portal/lift-videos'
      path: '/lift-videos'
      fullPath: '/portal/lift-videos'
      preLoaderRoute: typeof AuthenticatedPortalLiftVideosRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/exercises': {
      id: '/_authenticated/portal/exercises'
      path: '/exercises'
      fullPath: '/portal/exercises'
      preLoaderRoute: typeof AuthenticatedPortalExercisesRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/documents': {
      id: '/_authenticated/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof AuthenticatedPortalDocumentsRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/check-in': {
      id: '/_authenticated/portal/check-in'
      path: '/check-in'
      fullPath: '/portal/check-in'
      preLoaderRoute: typeof AuthenticatedPortalCheckInRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/calendar': {
      id: '/_authenticated/portal/calendar'
      path: '/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof AuthenticatedPortalCalendarRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/account': {
      id: '/_authenticated/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof AuthenticatedPortalAccountRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/training-phases': {
      id: '/_authenticated/admin/training-phases'
      path: '/training-phases'
      fullPath: '/admin/training-phases'
      preLoaderRoute: typeof AuthenticatedAdminTrainingPhasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sops': {
      id: '/_authenticated/admin/sops'
      path: '/sops'
      fullPath: '/admin/sops'
      preLoaderRoute: typeof AuthenticatedAdminSopsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/purchases': {
      id: '/_authenticated/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AuthenticatedAdminPurchasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/programs': {
      id: '/_authenticated/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AuthenticatedAdminProgramsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/nutrition-targets': {
      id: '/_authenticated/admin/nutrition-targets'
      path: '/nutrition-targets'
      fullPath: '/admin/nutrition-targets'
      preLoaderRoute: typeof AuthenticatedAdminNutritionTargetsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media-review': {
      id: '/_authenticated/admin/media-review'
      path: '/media-review'
      fullPath: '/admin/media-review'
      preLoaderRoute: typeof AuthenticatedAdminMediaReviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lift-videos': {
      id: '/_authenticated/admin/lift-videos'
      path: '/lift-videos'
      fullPath: '/admin/lift-videos'
      preLoaderRoute: typeof AuthenticatedAdminLiftVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/exercises': {
      id: '/_authenticated/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AuthenticatedAdminExercisesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content-ideas': {
      id: '/_authenticated/admin/content-ideas'
      path: '/content-ideas'
      fullPath: '/admin/content-ideas'
      preLoaderRoute: typeof AuthenticatedAdminContentIdeasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/check-ins': {
      id: '/_authenticated/admin/check-ins'
      path: '/check-ins'
      fullPath: '/admin/check-ins'
      preLoaderRoute: typeof AuthenticatedAdminCheckInsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cardio-targets': {
      id: '/_authenticated/admin/cardio-targets'
      path: '/cardio-targets'
      fullPath: '/admin/cardio-targets'
      preLoaderRoute: typeof AuthenticatedAdminCardioTargetsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/business-systems': {
      id: '/_authenticated/admin/business-systems'
      path: '/business-systems'
      fullPath: '/admin/business-systems'
      preLoaderRoute: typeof AuthenticatedAdminBusinessSystemsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/apps': {
      id: '/_authenticated/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AuthenticatedAdminAppsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portal/agreements/': {
      id: '/_authenticated/portal/agreements/'
      path: '/agreements'
      fullPath: '/portal/agreements/'
      preLoaderRoute: typeof AuthenticatedPortalAgreementsIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/admin/coaches/': {
      id: '/_authenticated/admin/coaches/'
      path: '/coaches'
      fullPath: '/admin/coaches/'
      preLoaderRoute: typeof AuthenticatedAdminCoachesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/agreements/': {
      id: '/_authenticated/admin/agreements/'
      path: '/agreements'
      fullPath: '/admin/agreements/'
      preLoaderRoute: typeof AuthenticatedAdminAgreementsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/portal/purchases/$id': {
      id: '/_authenticated/portal/purchases/$id'
      path: '/$id'
      fullPath: '/portal/purchases/$id'
      preLoaderRoute: typeof AuthenticatedPortalPurchasesIdRouteImport
      parentRoute: typeof AuthenticatedPortalPurchasesRoute
    }
    '/_authenticated/admin/purchases/$id': {
      id: '/_authenticated/admin/purchases/$id'
      path: '/$id'
      fullPath: '/admin/purchases/$id'
      preLoaderRoute: typeof AuthenticatedAdminPurchasesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPurchasesRoute
    }
    '/_authenticated/admin/coaches/$id': {
      id: '/_authenticated/admin/coaches/$id'
      path: '/coaches/$id'
      fullPath: '/admin/coaches/$id'
      preLoaderRoute: typeof AuthenticatedAdminCoachesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/agreements/signed': {
      id: '/_authenticated/admin/agreements/signed'
      path: '/agreements/signed'
      fullPath: '/admin/agreements/signed'
      preLoaderRoute: typeof AuthenticatedAdminAgreementsSignedRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminPurchasesRouteChildren {
  AuthenticatedAdminPurchasesIdRoute: typeof AuthenticatedAdminPurchasesIdRoute
}

const AuthenticatedAdminPurchasesRouteChildren: AuthenticatedAdminPurchasesRouteChildren =
  {
    AuthenticatedAdminPurchasesIdRoute: AuthenticatedAdminPurchasesIdRoute,
  }

const AuthenticatedAdminPurchasesRouteWithChildren =
  AuthenticatedAdminPurchasesRoute._addFileChildren(
    AuthenticatedAdminPurchasesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAppsRoute: typeof AuthenticatedAdminAppsRoute
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminBusinessSystemsRoute: typeof AuthenticatedAdminBusinessSystemsRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminCardioTargetsRoute: typeof AuthenticatedAdminCardioTargetsRoute
  AuthenticatedAdminCheckInsRoute: typeof AuthenticatedAdminCheckInsRoute
  AuthenticatedAdminContentIdeasRoute: typeof AuthenticatedAdminContentIdeasRoute
  AuthenticatedAdminExercisesRoute: typeof AuthenticatedAdminExercisesRoute
  AuthenticatedAdminLiftVideosRoute: typeof AuthenticatedAdminLiftVideosRoute
  AuthenticatedAdminMediaReviewRoute: typeof AuthenticatedAdminMediaReviewRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminNutritionTargetsRoute: typeof AuthenticatedAdminNutritionTargetsRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProgramsRoute: typeof AuthenticatedAdminProgramsRoute
  AuthenticatedAdminPurchasesRoute: typeof AuthenticatedAdminPurchasesRouteWithChildren
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSopsRoute: typeof AuthenticatedAdminSopsRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTrainingPhasesRoute: typeof AuthenticatedAdminTrainingPhasesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAgreementsSignedRoute: typeof AuthenticatedAdminAgreementsSignedRoute
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
  AuthenticatedAdminCoachesIdRoute: typeof AuthenticatedAdminCoachesIdRoute
  AuthenticatedAdminAgreementsIndexRoute: typeof AuthenticatedAdminAgreementsIndexRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
  AuthenticatedAdminCoachesIndexRoute: typeof AuthenticatedAdminCoachesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAppsRoute: AuthenticatedAdminAppsRoute,
    AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
    AuthenticatedAdminBusinessSystemsRoute:
      AuthenticatedAdminBusinessSystemsRoute,
    AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
    AuthenticatedAdminCardioTargetsRoute: AuthenticatedAdminCardioTargetsRoute,
    AuthenticatedAdminCheckInsRoute: AuthenticatedAdminCheckInsRoute,
    AuthenticatedAdminContentIdeasRoute: AuthenticatedAdminContentIdeasRoute,
    AuthenticatedAdminExercisesRoute: AuthenticatedAdminExercisesRoute,
    AuthenticatedAdminLiftVideosRoute: AuthenticatedAdminLiftVideosRoute,
    AuthenticatedAdminMediaReviewRoute: AuthenticatedAdminMediaReviewRoute,
    AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
    AuthenticatedAdminNutritionTargetsRoute:
      AuthenticatedAdminNutritionTargetsRoute,
    AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminProgramsRoute: AuthenticatedAdminProgramsRoute,
    AuthenticatedAdminPurchasesRoute:
      AuthenticatedAdminPurchasesRouteWithChildren,
    AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSopsRoute: AuthenticatedAdminSopsRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminTrainingPhasesRoute:
      AuthenticatedAdminTrainingPhasesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminAgreementsSignedRoute:
      AuthenticatedAdminAgreementsSignedRoute,
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
    AuthenticatedAdminCoachesIdRoute: AuthenticatedAdminCoachesIdRoute,
    AuthenticatedAdminAgreementsIndexRoute:
      AuthenticatedAdminAgreementsIndexRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
    AuthenticatedAdminCoachesIndexRoute: AuthenticatedAdminCoachesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedPortalPurchasesRouteChildren {
  AuthenticatedPortalPurchasesIdRoute: typeof AuthenticatedPortalPurchasesIdRoute
}

const AuthenticatedPortalPurchasesRouteChildren: AuthenticatedPortalPurchasesRouteChildren =
  {
    AuthenticatedPortalPurchasesIdRoute: AuthenticatedPortalPurchasesIdRoute,
  }

const AuthenticatedPortalPurchasesRouteWithChildren =
  AuthenticatedPortalPurchasesRoute._addFileChildren(
    AuthenticatedPortalPurchasesRouteChildren,
  )

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalAccountRoute: typeof AuthenticatedPortalAccountRoute
  AuthenticatedPortalCalendarRoute: typeof AuthenticatedPortalCalendarRoute
  AuthenticatedPortalCheckInRoute: typeof AuthenticatedPortalCheckInRoute
  AuthenticatedPortalDocumentsRoute: typeof AuthenticatedPortalDocumentsRoute
  AuthenticatedPortalExercisesRoute: typeof AuthenticatedPortalExercisesRoute
  AuthenticatedPortalLiftVideosRoute: typeof AuthenticatedPortalLiftVideosRoute
  AuthenticatedPortalMediaRoute: typeof AuthenticatedPortalMediaRoute
  AuthenticatedPortalMessagesRoute: typeof AuthenticatedPortalMessagesRoute
  AuthenticatedPortalNutritionTargetsRoute: typeof AuthenticatedPortalNutritionTargetsRoute
  AuthenticatedPortalPaymentsRoute: typeof AuthenticatedPortalPaymentsRoute
  AuthenticatedPortalProgramRoute: typeof AuthenticatedPortalProgramRoute
  AuthenticatedPortalPurchasesRoute: typeof AuthenticatedPortalPurchasesRouteWithChildren
  AuthenticatedPortalResourcesRoute: typeof AuthenticatedPortalResourcesRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalAgreementsIndexRoute: typeof AuthenticatedPortalAgreementsIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalAccountRoute: AuthenticatedPortalAccountRoute,
    AuthenticatedPortalCalendarRoute: AuthenticatedPortalCalendarRoute,
    AuthenticatedPortalCheckInRoute: AuthenticatedPortalCheckInRoute,
    AuthenticatedPortalDocumentsRoute: AuthenticatedPortalDocumentsRoute,
    AuthenticatedPortalExercisesRoute: AuthenticatedPortalExercisesRoute,
    AuthenticatedPortalLiftVideosRoute: AuthenticatedPortalLiftVideosRoute,
    AuthenticatedPortalMediaRoute: AuthenticatedPortalMediaRoute,
    AuthenticatedPortalMessagesRoute: AuthenticatedPortalMessagesRoute,
    AuthenticatedPortalNutritionTargetsRoute:
      AuthenticatedPortalNutritionTargetsRoute,
    AuthenticatedPortalPaymentsRoute: AuthenticatedPortalPaymentsRoute,
    AuthenticatedPortalProgramRoute: AuthenticatedPortalProgramRoute,
    AuthenticatedPortalPurchasesRoute:
      AuthenticatedPortalPurchasesRouteWithChildren,
    AuthenticatedPortalResourcesRoute: AuthenticatedPortalResourcesRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
    AuthenticatedPortalAgreementsIndexRoute:
      AuthenticatedPortalAgreementsIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SitemapRoute: SitemapRoute,
  ApiPublicSignnowWebhookRoute: ApiPublicSignnowWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
