-- Messaging: three independent concepts.
--   1. COACH UNREAD      per staff member: has *this* coach seen the client's new inbound activity?
--   2. CLIENT READ       messages.read_by_client_at (set only when the client views the conversation)
--   3. COACH WORKFLOW    conversation_state.workflow_status: needs_response | waiting_on_client | done
-- Unread never changes workflow; workflow never changes unread.

-- ---------------------------------------------------------------------------
-- Automated outbound messages (check-in / nutrition reminders) are flagged so
-- they never look like the coach's own work and never create coach attention.
-- ---------------------------------------------------------------------------
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS is_automated boolean NOT NULL DEFAULT false;

CREATE OR REPLACE FUNCTION public.message_attachment_kinds(_attachments jsonb)
RETURNS text[] LANGUAGE sql IMMUTABLE SET search_path = public AS $$
  SELECT coalesce(array_agg(a->>'kind') FILTER (WHERE a->>'kind' IS NOT NULL), '{}')
    FROM jsonb_array_elements(CASE WHEN jsonb_typeof(_attachments) = 'array' THEN _attachments ELSE '[]'::jsonb END) a
$$;

CREATE OR REPLACE FUNCTION public.tg_messages_flag_automated()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.sender_role = 'admin'
     AND 'checkin_request' = ANY(public.message_attachment_kinds(NEW.attachments))
     AND coalesce(NEW.body,'') ~* '^quick (60-second weekly|monthly nutrition) check-in' THEN
    NEW.is_automated := true;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_messages_flag_automated ON public.messages;
CREATE TRIGGER trg_messages_flag_automated BEFORE INSERT ON public.messages
FOR EACH ROW EXECUTE FUNCTION public.tg_messages_flag_automated();

UPDATE public.messages SET is_automated = true
 WHERE NOT is_automated AND sender_role = 'admin'
   AND 'checkin_request' = ANY(public.message_attachment_kinds(attachments))
   AND coalesce(body,'') ~* '^quick (60-second weekly|monthly nutrition) check-in';

-- ---------------------------------------------------------------------------
-- Workflow status (conversation level) + lightweight history.
-- ---------------------------------------------------------------------------
ALTER TABLE public.conversation_state
  ADD COLUMN IF NOT EXISTS workflow_status text NOT NULL DEFAULT 'done',
  ADD COLUMN IF NOT EXISTS workflow_status_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS workflow_status_updated_by uuid,
  ADD COLUMN IF NOT EXISTS workflow_reason text,
  ADD COLUMN IF NOT EXISTS last_inbound_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_inbound_kind text;
DO $$ BEGIN
  ALTER TABLE public.conversation_state ADD CONSTRAINT conversation_state_workflow_status_check
    CHECK (workflow_status IN ('needs_response','waiting_on_client','done'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.conversation_workflow_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  workflow_status text NOT NULL,
  reason text NOT NULL,
  actor_id uuid,
  message_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS conversation_workflow_events_client_idx ON public.conversation_workflow_events (client_id, created_at DESC);
ALTER TABLE public.conversation_workflow_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff read workflow events" ON public.conversation_workflow_events;
CREATE POLICY "Staff read workflow events" ON public.conversation_workflow_events FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'admin') OR public.is_assigned_coach(client_id));

-- Single writer for workflow changes. Records history only when the status changes.
CREATE OR REPLACE FUNCTION public.apply_conversation_workflow(
  _client_id uuid, _status text, _reason text, _actor uuid, _message_id uuid DEFAULT NULL,
  _only_if_not_needs_response boolean DEFAULT false, _at timestamptz DEFAULT now())
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE cur text;
BEGIN
  INSERT INTO public.conversation_state (client_id, workflow_status, workflow_status_updated_at, workflow_status_updated_by, workflow_reason)
  VALUES (_client_id, _status, _at, _actor, _reason)
  ON CONFLICT (client_id) DO NOTHING
  RETURNING NULL INTO cur;
  IF FOUND THEN
    INSERT INTO public.conversation_workflow_events (client_id, workflow_status, reason, actor_id, message_id, created_at)
    VALUES (_client_id, _status, _reason, _actor, _message_id, _at);
    RETURN;
  END IF;
  SELECT workflow_status INTO cur FROM public.conversation_state WHERE client_id = _client_id FOR UPDATE;
  IF _only_if_not_needs_response AND cur = 'needs_response' THEN RETURN; END IF;
  IF cur IS DISTINCT FROM _status THEN
    UPDATE public.conversation_state
       SET workflow_status = _status, workflow_status_updated_at = _at,
           workflow_status_updated_by = _actor, workflow_reason = _reason, updated_at = now()
     WHERE client_id = _client_id;
    INSERT INTO public.conversation_workflow_events (client_id, workflow_status, reason, actor_id, message_id, created_at)
    VALUES (_client_id, _status, _reason, _actor, _message_id, _at);
  END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.apply_conversation_workflow(uuid, text, text, uuid, uuid, boolean, timestamptz) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.note_inbound_activity(_client_id uuid, _kind text, _at timestamptz)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.conversation_state (client_id, last_inbound_at, last_inbound_kind)
  VALUES (_client_id, _at, _kind)
  ON CONFLICT (client_id) DO UPDATE
    SET last_inbound_at = GREATEST(coalesce(public.conversation_state.last_inbound_at, EXCLUDED.last_inbound_at), EXCLUDED.last_inbound_at),
        last_inbound_kind = CASE WHEN public.conversation_state.last_inbound_at IS NULL
                                   OR EXCLUDED.last_inbound_at >= public.conversation_state.last_inbound_at
                                 THEN EXCLUDED.last_inbound_kind ELSE public.conversation_state.last_inbound_kind END,
        updated_at = now();
END;
$$;
REVOKE ALL ON FUNCTION public.note_inbound_activity(uuid, text, timestamptz) FROM PUBLIC, anon, authenticated;

-- Messages drive the workflow:
--   client message / check-in submission → NEEDS RESPONSE (+ inbound activity)
--   coach reply                           → WAITING ON CLIENT
--   automated reminder / request card     → WAITING ON CLIENT, but never clears an open NEEDS RESPONSE
CREATE OR REPLACE FUNCTION public.tg_messages_workflow()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE kinds text[];
BEGIN
  IF NEW.is_internal_note OR coalesce(NEW.delivery_status, 'sent') NOT IN ('sent', 'sending') THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND coalesce(OLD.delivery_status, 'sent') IN ('sent', 'sending') THEN RETURN NEW; END IF;
  kinds := public.message_attachment_kinds(NEW.attachments);
  IF NEW.sender_role = 'client' THEN
    PERFORM public.note_inbound_activity(NEW.client_id,
      CASE WHEN 'checkin_submission' = ANY(kinds) THEN 'checkin' ELSE 'message' END, NEW.created_at);
    PERFORM public.apply_conversation_workflow(NEW.client_id, 'needs_response',
      CASE WHEN 'checkin_submission' = ANY(kinds) THEN 'checkin_submitted' ELSE 'client_message' END,
      NEW.sender_id, NEW.id, false, NEW.created_at);
  ELSIF NEW.is_automated OR kinds && ARRAY['checkin_request','form_request','signature_request'] THEN
    PERFORM public.apply_conversation_workflow(NEW.client_id, 'waiting_on_client',
      CASE WHEN NEW.is_automated THEN 'automated_request' ELSE 'request_sent' END,
      CASE WHEN NEW.is_automated THEN NULL ELSE NEW.sender_id END, NEW.id, true, NEW.created_at);
  ELSE
    PERFORM public.apply_conversation_workflow(NEW.client_id, 'waiting_on_client', 'coach_replied',
      NEW.sender_id, NEW.id, false, NEW.created_at);
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_messages_workflow ON public.messages;
CREATE TRIGGER trg_messages_workflow AFTER INSERT OR UPDATE OF delivery_status ON public.messages
FOR EACH ROW EXECUTE FUNCTION public.tg_messages_workflow();

-- Native form submissions and lift uploads are inbound client activity too.
CREATE OR REPLACE FUNCTION public.tg_nf_submissions_workflow()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.client_id IS NULL OR NEW.submitted_at IS NULL THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND OLD.submitted_at IS NOT DISTINCT FROM NEW.submitted_at THEN RETURN NEW; END IF;
  PERFORM public.note_inbound_activity(NEW.client_id, 'form', NEW.submitted_at);
  PERFORM public.apply_conversation_workflow(NEW.client_id, 'needs_response', 'form_submitted', NULL, NULL, false, NEW.submitted_at);
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_nf_submissions_workflow ON public.nf_submissions;
CREATE TRIGGER trg_nf_submissions_workflow AFTER INSERT OR UPDATE OF submitted_at ON public.nf_submissions
FOR EACH ROW EXECUTE FUNCTION public.tg_nf_submissions_workflow();

CREATE OR REPLACE FUNCTION public.tg_lift_videos_workflow()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.client_id IS NULL OR coalesce(NEW.archived, false) THEN RETURN NEW; END IF;
  PERFORM public.note_inbound_activity(NEW.client_id, 'lift_video', NEW.created_at);
  PERFORM public.apply_conversation_workflow(NEW.client_id, 'needs_response', 'lift_video_uploaded', NULL, NULL, false, NEW.created_at);
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_lift_videos_workflow ON public.lift_videos;
CREATE TRIGGER trg_lift_videos_workflow AFTER INSERT ON public.lift_videos
FOR EACH ROW EXECUTE FUNCTION public.tg_lift_videos_workflow();

-- ---------------------------------------------------------------------------
-- Per-staff read state (coach A reading does not clear coach B's dot).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.conversation_staff_reads (
  client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
  user_id uuid NOT NULL,
  last_read_at timestamptz,
  manual_unread boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (client_id, user_id)
);
ALTER TABLE public.conversation_staff_reads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Staff read own read state" ON public.conversation_staff_reads;
CREATE POLICY "Staff read own read state" ON public.conversation_staff_reads FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE OR REPLACE FUNCTION public.can_staff_conversation(_client_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT public.has_role(auth.uid(), 'admin') OR public.is_assigned_coach(_client_id)
$$;

CREATE OR REPLACE FUNCTION public.staff_mark_conversation_read(_client_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.can_staff_conversation(_client_id) THEN RAISE EXCEPTION 'Not allowed' USING ERRCODE = '42501'; END IF;
  INSERT INTO public.conversation_staff_reads (client_id, user_id, last_read_at, manual_unread, updated_at)
  VALUES (_client_id, auth.uid(), now(), false, now())
  ON CONFLICT (client_id, user_id) DO UPDATE SET last_read_at = now(), manual_unread = false, updated_at = now();
END;
$$;
GRANT EXECUTE ON FUNCTION public.staff_mark_conversation_read(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.staff_mark_conversation_unread(_client_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.can_staff_conversation(_client_id) THEN RAISE EXCEPTION 'Not allowed' USING ERRCODE = '42501'; END IF;
  INSERT INTO public.conversation_staff_reads (client_id, user_id, manual_unread, updated_at)
  VALUES (_client_id, auth.uid(), true, now())
  ON CONFLICT (client_id, user_id) DO UPDATE SET manual_unread = true, updated_at = now();
END;
$$;
GRANT EXECUTE ON FUNCTION public.staff_mark_conversation_unread(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.set_conversation_workflow(_client_id uuid, _status text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT public.can_staff_conversation(_client_id) THEN RAISE EXCEPTION 'Not allowed' USING ERRCODE = '42501'; END IF;
  IF _status NOT IN ('needs_response','waiting_on_client','done') THEN RAISE EXCEPTION 'Unknown status %', _status; END IF;
  PERFORM public.apply_conversation_workflow(_client_id, _status, 'manual', auth.uid(), NULL, false, now());
  -- A manual decision is always recorded, even if the status didn't change.
  UPDATE public.conversation_state SET workflow_status_updated_at = now(), workflow_status_updated_by = auth.uid(), workflow_reason = 'manual'
   WHERE client_id = _client_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.set_conversation_workflow(uuid, text) TO authenticated;

-- Everything the inbox, filter counts and nav badge need, for the calling staff member.
CREATE OR REPLACE FUNCTION public.staff_inbox_state()
RETURNS TABLE(client_id uuid, workflow_status text, workflow_reason text, workflow_status_updated_at timestamptz,
              workflow_updated_by_name text, last_inbound_at timestamptz, last_inbound_kind text,
              my_last_read_at timestamptz, unread boolean, unread_count int, archived boolean)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE me uuid := auth.uid(); is_admin boolean;
BEGIN
  IF me IS NULL THEN RAISE EXCEPTION 'Not allowed' USING ERRCODE = '42501'; END IF;
  is_admin := public.has_role(me, 'admin');
  IF NOT is_admin AND NOT public.has_role(me, 'coach') THEN RAISE EXCEPTION 'Not allowed' USING ERRCODE = '42501'; END IF;
  RETURN QUERY
  WITH cs AS (
    SELECT s.*, coalesce(r.last_read_at, s.admin_last_read_at) AS read_at, coalesce(r.manual_unread, false) AS manual
      FROM public.conversation_state s
      LEFT JOIN public.conversation_staff_reads r ON r.client_id = s.client_id AND r.user_id = me
     WHERE is_admin OR public.is_assigned_coach(s.client_id)
  )
  SELECT cs.client_id, cs.workflow_status, cs.workflow_reason, cs.workflow_status_updated_at,
         (SELECT coalesce(nullif(btrim(coalesce(p.full_name, '')), ''), 'Coach') FROM public.coaches p WHERE p.user_id = cs.workflow_status_updated_by LIMIT 1),
         cs.last_inbound_at, cs.last_inbound_kind, cs.read_at,
         cs.manual OR (cs.last_inbound_at IS NOT NULL AND cs.last_inbound_at > coalesce(cs.read_at, '-infinity'::timestamptz)),
         GREATEST(
           (SELECT count(*)::int FROM public.messages m
             WHERE m.client_id = cs.client_id AND m.sender_role = 'client' AND NOT m.is_internal_note
               AND m.created_at > coalesce(cs.read_at, '-infinity'::timestamptz)),
           CASE WHEN cs.manual OR (cs.last_inbound_at > coalesce(cs.read_at, '-infinity'::timestamptz)) THEN 1 ELSE 0 END),
         cs.status = 'archived'
    FROM cs;
END;
$$;
GRANT EXECUTE ON FUNCTION public.staff_inbox_state() TO authenticated;

CREATE INDEX IF NOT EXISTS messages_client_sender_created_idx ON public.messages (client_id, sender_role, created_at DESC);

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.conversation_staff_reads;
EXCEPTION WHEN duplicate_object OR undefined_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- Backfill (no fabricated read receipts: read_by_client_at is left as recorded).
-- ---------------------------------------------------------------------------
INSERT INTO public.conversation_state (client_id)
SELECT DISTINCT m.client_id FROM public.messages m
 WHERE NOT EXISTS (SELECT 1 FROM public.conversation_state s WHERE s.client_id = m.client_id)
ON CONFLICT DO NOTHING;

WITH inbound AS (
  SELECT client_id, max(at) at FROM (
    SELECT client_id, created_at at FROM public.messages WHERE sender_role = 'client' AND NOT is_internal_note
    UNION ALL SELECT client_id, submitted_at FROM public.nf_submissions WHERE submitted_at IS NOT NULL AND client_id IS NOT NULL
  ) x GROUP BY 1
), last_msg AS (
  SELECT DISTINCT ON (client_id) client_id, sender_role, is_automated, created_at
    FROM public.messages
   WHERE NOT is_internal_note AND coalesce(delivery_status, 'sent') IN ('sent', 'sending')
   ORDER BY client_id, created_at DESC
), last_human AS (
  SELECT DISTINCT ON (client_id) client_id, sender_role, created_at
    FROM public.messages
   WHERE NOT is_internal_note AND NOT is_automated AND coalesce(delivery_status, 'sent') IN ('sent', 'sending')
   ORDER BY client_id, created_at DESC
), pending_form AS (
  SELECT f.client_id, max(f.submitted_at) at FROM public.nf_submissions f
   WHERE f.submitted_at IS NOT NULL AND f.reviewed_at IS NULL AND f.client_id IS NOT NULL GROUP BY 1
)
UPDATE public.conversation_state s SET
  last_inbound_at = i.at,
  workflow_status = CASE
    WHEN s.status = 'resolved' THEN 'done'
    WHEN lh.sender_role = 'client' THEN 'needs_response'
    WHEN pf.at IS NOT NULL AND pf.at > coalesce((SELECT max(created_at) FROM public.messages m WHERE m.client_id = s.client_id AND m.sender_role = 'admin' AND NOT m.is_automated AND NOT m.is_internal_note), '-infinity') THEN 'needs_response'
    WHEN lm.sender_role = 'admin' THEN 'waiting_on_client'
    ELSE 'done' END,
  workflow_reason = 'backfill',
  workflow_status_updated_at = coalesce(lm.created_at, s.updated_at),
  priority = CASE WHEN s.priority = 'Needs Response' THEN 'Normal' ELSE s.priority END
FROM public.conversation_state s2
LEFT JOIN inbound i ON i.client_id = s2.client_id
LEFT JOIN last_msg lm ON lm.client_id = s2.client_id
LEFT JOIN last_human lh ON lh.client_id = s2.client_id
LEFT JOIN pending_form pf ON pf.client_id = s2.client_id
WHERE s.client_id = s2.client_id AND s.workflow_reason IS NULL;

-- Existing global read position becomes every current staff member's own starting point.
INSERT INTO public.conversation_staff_reads (client_id, user_id, last_read_at)
SELECT s.client_id, ur.user_id, s.admin_last_read_at
  FROM public.conversation_state s
  JOIN public.user_roles ur ON ur.role IN ('admin', 'coach')
 WHERE s.admin_last_read_at IS NOT NULL
ON CONFLICT DO NOTHING;
