-- New exercises are tagged by the same rules as the app.
--
-- public.exercise_classify() below is GENERATED from src/lib/exercise-classifier.ts
-- (exerciseClassifierSql() in src/lib/exercise-classifier-sql.ts); a test fails if
-- the two drift. It replaces the older hand-written exercise_muscle_profile rules,
-- so every insert path (library form, bulk import, quick swap, raw SQL) gets the
-- same pattern, muscles, volume flag and equipment the 2026-10-07 backfill set.

-- GENERATED by exerciseClassifierSql() in src/lib/exercise-classifier-sql.ts — do not hand-edit.
CREATE OR REPLACE FUNCTION public.exercise_classify(_name text, _category text DEFAULT NULL)
 RETURNS TABLE(pattern text, primary_muscles text[], secondary_muscles text[], equipment text, matched boolean)
 LANGUAGE plpgsql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $fn$
DECLARE
  n text := ' ' || btrim(regexp_replace(lower(coalesce(_name, '')), '[^a-z0-9]+', ' ', 'g')) || ' ';
  c text := lower(coalesce(_category, ''));
  p text;
  pm text[];
  sm text[];
  eq text;
BEGIN
  eq := CASE
      WHEN n ~ ' smith ' THEN 'Smith Machine'
      WHEN n ~ ' (barbell|bb|ez bar|ez|trap bar|hex bar|safety bar|ssb|landmine|axle|cambered|swiss bar|football bar) ' THEN 'Barbell'
      WHEN n ~ ' (dumbbell|dumbbells|db) ' THEN 'Dumbbell'
      WHEN n ~ ' (kettlebell|kettlebells|kb) ' THEN 'Kettlebell'
      WHEN n ~ ' (cable|cables|rope|pulldown|pull down|lat pull|pushdown|push down|crossover) ' THEN 'Cable'
      WHEN n ~ ' (band|bands|banded|resistance band|mini band) ' THEN 'Bands'
      WHEN n ~ ' (machine|hammer strength|leg press|hack squat|pendulum|belt squat|pec deck|selectorized|plate loaded|seated row machine|chest supported row machine|multi hip|glute ham|ghd|reverse hyper|leg extension|leg curl) ' THEN 'Machine'
      WHEN n ~ ' (push up|pushup|pull up|pullup|chin up|chinup|dip|dips|plank|bodyweight|bw|air squat|inverted row|nordic|sit up|situp|crunch|burpee|jump|hollow|l sit|muscle up|pistol) ' THEN 'Bodyweight'
    END;
  IF n ~ 'stretch|mobility|yoga|pose|foam roll|smr|lacrosse ball|release|cat cow|90 90|world s greatest|thread the needle|circles|dislocat| cars |basic toe touch|standing toe touch|forward fold' THEN
    p := 'mobility'; pm := ARRAY['other']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (walk|walking|jog|jogging|run|running|sprint|bike|cycling|airbike|assault|row erg|rowing machine|ski erg|ski ergometer|elliptical|stair|treadmill|jump rope|skipping|jumping jack|battle rope|agility|shadow box|punch|punches|march|marching|sled push|prowler|ball slam|slams|burpee) ' THEN
    p := 'conditioning'; pm := ARRAY['other']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (clean|snatch|jerk|high pull) ' AND n !~ ' (grip deadlift|snatch deadlift|clean deadlift) ' THEN
    p := 'olympic'; pm := ARRAY['quads', 'glutes', 'traps']::text[]; sm := ARRAY['hamstrings', 'upper_back', 'calves']::text[];
  ELSIF n ~ ' (clap push|plyo push|plyometric push) ' THEN
    p := 'horizontal_press'; pm := ARRAY['chest', 'triceps']::text[]; sm := ARRAY['front_delts']::text[];
  ELSIF n ~ ' (box jump|broad jump|depth jump|jump squat|squat jump|tuck jump|bound|bounding|pogo|plyo|med ball throw|medicine ball throw|lateral hop|skater jump) ' THEN
    p := 'plyometric'; pm := ARRAY['quads', 'glutes']::text[]; sm := ARRAY['calves']::text[];
  ELSIF n ~ ' (copenhagen|adduction|adductor|adductors|hip adduct|groin squeeze|inner thigh) ' THEN
    p := 'hip_adduction'; pm := ARRAY['adductors']::text[]; sm := ARRAY['core']::text[];
  ELSIF n ~ ' (abduction|abductor|abductors|clamshell|clam shell|clams?|fire hydrants?|monster walks?|lateral band walks?|band walks?|crab walks?|side lying leg (raise|lift)s?|side lying hip raises?|standing side leg raises?|side kicks?) ' THEN
    p := 'hip_abduction'; pm := ARRAY['glutes']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (hip flexion|hip flexor march|psoas march) ' THEN
    p := 'hip_flexion'; pm := ARRAY['core']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (glute kick ?backs?|kickback glute|donkey kicks?|glute medius kickback|hip extension|glute extension|cable kickback|reverse lunge kickback|quadruped kickback|rear kicks?) ' AND n !~ ' pullover ' THEN
    p := 'hip_thrust'; pm := ARRAY['glutes']::text[]; sm := ARRAY['hamstrings']::text[];
  ELSIF n ~ ' ((external|internal) (shoulder )?rotation?|rotator|cuban|no money) ' THEN
    p := 'rear_delt'; pm := ARRAY['rear_delts']::text[]; sm := ARRAY['upper_back']::text[];
  ELSIF n ~ ' (upward rotation|scapular elevation) ' THEN
    p := 'shrug'; pm := ARRAY['traps']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (wrist curl|wrist extension|reverse wrist|wrist roller|pronation|supination|palm up palm down|gripper|grip trainer|grip strength|hand grip|dead hang|plate pinch|farmer s hold) ' THEN
    p := 'wrist'; pm := ARRAY['forearms']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (calf|calves|calve|heel raises?|donkey raises?|tibialis|tib raises?|toe raises?|plantar flexion|dorsal flexion) ' THEN
    p := 'calf_raise'; pm := ARRAY['calves']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (mountain climber) ' THEN
    p := 'core_flexion'; pm := ARRAY['core']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (nordic|glute ham raise|ghr|leg curl|hamstring curl|lying curl|seated curl machine|slider curl|stability ball curl|swiss ball leg curl|ball leg curl) ' THEN
    p := 'knee_flexion'; pm := ARRAY['hamstrings']::text[]; sm := ARRAY['calves']::text[];
  ELSIF n ~ ' (hip thrusts?|hip thrusters?|glute bridges?|frog pumps?|kas glute|glute drive|bridge) ' THEN
    p := 'hip_thrust'; pm := ARRAY['glutes']::text[]; sm := ARRAY['hamstrings']::text[];
  ELSIF n ~ ' (romanian|rdl|stiff leg|stiff legged|sldl|good mornings?|single leg deadlift|b stance deadlift|kickstand deadlift) ' THEN
    p := 'hinge'; pm := ARRAY['hamstrings', 'glutes']::text[]; sm := ARRAY['lower_back', 'forearms']::text[];
  ELSIF n ~ ' (back extension|hyperextension|hyper extension|reverse hyper|45 degree (back|hyper|glute)|superman|bird dog) ' THEN
    p := 'back_extension'; pm := ARRAY['lower_back', 'glutes']::text[]; sm := ARRAY['hamstrings']::text[];
  ELSIF n ~ ' (kettlebell swings?|kb swings?|dumbbell swings?|pull ?throughs?) ' THEN
    p := 'hinge'; pm := ARRAY['glutes', 'hamstrings']::text[]; sm := ARRAY['lower_back', 'core']::text[];
  ELSIF n ~ ' (trap bar deadlift|hex bar deadlift|trap bar pull) ' THEN
    p := 'hinge'; pm := ARRAY['quads', 'glutes', 'hamstrings']::text[]; sm := ARRAY['lower_back', 'traps', 'forearms']::text[];
  ELSIF n ~ ' (deadlifts?|rack pulls?|block pulls?|deficit pulls?) ' THEN
    p := 'hinge'; pm := ARRAY['glutes', 'hamstrings', 'lower_back']::text[]; sm := ARRAY['quads', 'upper_back', 'traps', 'forearms', 'adductors']::text[];
  ELSIF n ~ ' (leg extension|knee extension|sissy squat|reverse nordic|spanish squat|terminal knee) ' THEN
    p := 'knee_extension'; pm := ARRAY['quads']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (bench dip|chair dip|triceps dip|tricep dip|dip on floor|between chairs|floor dip|couch) ' THEN
    p := 'dip'; pm := ARRAY['triceps']::text[]; sm := ARRAY['chest', 'front_delts']::text[];
  ELSIF n ~ ' (reverse curl|hammer curl|zottman) ' THEN
    p := 'elbow_flexion'; pm := ARRAY['biceps', 'forearms']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (curl|curls) ' THEN
    p := 'elbow_flexion'; pm := ARRAY['biceps']::text[]; sm := ARRAY['forearms']::text[];
  ELSIF n ~ ' (jm press|close grip bench|close grip press|cg bench|close grip floor press|close grip push up|diamond push up|tate press) ' THEN
    p := 'horizontal_press'; pm := ARRAY['triceps', 'chest']::text[]; sm := ARRAY['front_delts']::text[];
  ELSIF n ~ ' (tricep|triceps|pushdown|push down|skull crusher|skullcrusher|kickback|french press|overhead extension|lying extension|elbow extension) ' THEN
    p := 'elbow_extension'; pm := ARRAY['triceps']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (face ?pulls?|rear delt|rear deltoid|reverse fly|reverse flye|reverse machine fly|reverse cable fly|reverse dumbbell fly|rear fly|rear lateral|reverse pec deck|band pull apart|pull apart|bent over fly|bent over raise|bent over lateral|prone t|t raise|w raise|breeding) ' THEN
    p := 'rear_delt'; pm := ARRAY['rear_delts']::text[]; sm := ARRAY['upper_back']::text[];
  ELSIF n ~ ' (upright rows?) ' THEN
    p := 'lateral_raise'; pm := ARRAY['side_delts', 'traps']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (lateral raises?|side raises?|lat raises?|lateral delt|lu raises?|shoulder abduction|iron cross|y raises?|prone y|side lying one hand raise) ' THEN
    p := 'lateral_raise'; pm := ARRAY['side_delts']::text[]; sm := ARRAY['traps']::text[];
  ELSIF n ~ ' (front raises?|plate raises?|shoulder flexion|alternate raises?|vertical front raises?|cross raises?) ' THEN
    p := 'front_raise'; pm := ARRAY['front_delts']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (shrug|shrugs) ' THEN
    p := 'shrug'; pm := ARRAY['traps']::text[]; sm := ARRAY['forearms']::text[];
  ELSIF n ~ ' (wall sit|lunge|lunges|split squat|bulgarian|step up|stepup|step ups|step down|curtsy|pistol|skater squat|single leg squat|rear foot elevated|rfess) ' THEN
    p := 'lunge'; pm := ARRAY['quads', 'glutes']::text[]; sm := ARRAY['adductors', 'hamstrings']::text[];
  ELSIF n ~ ' (thrusters?) ' THEN
    p := 'squat'; pm := ARRAY['quads', 'glutes', 'front_delts']::text[]; sm := ARRAY['triceps', 'core']::text[];
  ELSIF n ~ ' (leg press|hack squat|pendulum squat|belt squat|v squat) ' THEN
    p := 'squat'; pm := ARRAY['quads', 'glutes']::text[]; sm := ARRAY['adductors']::text[];
  ELSIF n ~ ' (front squat|goblet squat|zercher|cyclist squat|heel elevated squat|high bar|highbar) ' THEN
    p := 'squat'; pm := ARRAY['quads', 'glutes']::text[]; sm := ARRAY['adductors', 'upper_back', 'core']::text[];
  ELSIF n ~ ' (squat|squats) ' THEN
    p := 'squat'; pm := ARRAY['quads', 'glutes', 'adductors']::text[]; sm := ARRAY['lower_back', 'core']::text[];
  ELSIF n ~ ' (pullover|pull over|straight arm pulldown|straight arm pull down|lat prayer|shoulder adduction|shoulder extension) ' THEN
    p := 'pullover'; pm := ARRAY['lats']::text[]; sm := ARRAY['chest', 'triceps']::text[];
  ELSIF n ~ ' (pull up|pullup|pull ups|pullups|chin up|chinup|chin ups|pulldown|pull down|lat pull|muscle up) ' THEN
    p := 'vertical_pull'; pm := ARRAY['lats']::text[]; sm := ARRAY['biceps', 'upper_back']::text[];
  ELSIF n ~ ' (row|rows|seal row|pendlay|meadows|kroc|t bar|renegade) ' THEN
    p := 'horizontal_pull'; pm := ARRAY['upper_back', 'lats']::text[]; sm := ARRAY['rear_delts', 'biceps']::text[];
  ELSIF n ~ ' (dip|dips) ' THEN
    p := 'dip'; pm := ARRAY['chest', 'triceps']::text[]; sm := ARRAY['front_delts']::text[];
  ELSIF n ~ ' (fly|flye|flyes|flys|pec deck|crossovers?|cross over|squeeze fly|high to low|low to high) ' THEN
    p := 'chest_fly'; pm := ARRAY['chest']::text[]; sm := ARRAY['front_delts']::text[];
  ELSIF n ~ ' (overhead press|ohp|military press|shoulder press|shoulders press|shoulder pres|push press|strict press|arnold press|landmine press|landmine alternating single arm press|z press|seated press|seated alternate press|alternate side press|palms in press|scott press|w press|y press|seesaw press|behind neck press|anti gravity press|press under|viking press|pike push ups?|handstand push|hspu) ' THEN
    p := 'vertical_press'; pm := ARRAY['front_delts']::text[]; sm := ARRAY['triceps', 'side_delts']::text[];
  ELSIF n ~ ' incline ' AND n ~ '(press|push up|pushup)' THEN
    p := 'incline_press'; pm := ARRAY['chest', 'front_delts']::text[]; sm := ARRAY['triceps']::text[];
  ELSIF n ~ ' (bench press|competition bench|dead bench|paused? bench|flat bench|touch and go bench|floor press|spoto|spotto|larsen|pin press|board press|chest press|push up|pushup|push ups|pushups|press up|svend|plate press|squeeze press|hex press|decline press|decline hammer press|decline one arm hammer press|decline bench|close neutral grip press|dumbbell press|db press|machine press|band press) ' THEN
    p := 'horizontal_press'; pm := ARRAY['chest', 'triceps']::text[]; sm := ARRAY['front_delts']::text[];
  ELSIF n ~ ' (farmer|farmers|suitcase carry|carry|carries|yoke) ' THEN
    p := 'carry'; pm := ARRAY['forearms', 'traps', 'core']::text[]; sm := ARRAY['glutes']::text[];
  ELSIF n ~ ' (side plank|side bends?|oblique|windmill) ' THEN
    p := 'core_lateral'; pm := ARRAY['core']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (plank|ab wheel|rollout|roll out|dead bug|deadbug|hollow|body saw|stir the pot|bear hold|l sit) ' THEN
    p := 'core_anti_extension'; pm := ARRAY['core']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (pallof|palloff|woodchop|wood chop|wood choppers?|diagonal chop|chop|russian twist|rotation|rotational|twist|twisting|landmine 180|anti rotation) ' THEN
    p := 'core_rotation'; pm := ARRAY['core']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (front lever|back lever|dragon flag) ' THEN
    p := 'core_anti_extension'; pm := ARRAY['core', 'lats']::text[]; sm := '{}'::text[];
  ELSIF n ~ ' (turkish get ?up|tgu) ' THEN
    p := 'core_lateral'; pm := ARRAY['core', 'front_delts']::text[]; sm := ARRAY['glutes']::text[];
  ELSIF n ~ ' (handstand hold|hand stand hold) ' THEN
    p := 'vertical_press'; pm := ARRAY['front_delts']::text[]; sm := ARRAY['triceps', 'core']::text[];
  ELSIF n ~ ' (crunch|crunches|sit up|situp|sit ups|situps|leg raises?|knee raises?|toes to bar|v up|vup|flutter|scissors?|toe touch|toe touches|jackknife|jack knives|hanging raise|mountain climbers?|heel touch|heel touches|knee tucks?|bicycles?|wind wipers|dragonfly|leg lifts?|toe taps?|abs|ab) ' THEN
    p := 'core_flexion'; pm := ARRAY['core']::text[]; sm := '{}'::text[];
  ELSIF position('stretch' in c) > 0 OR c = 'yoga' THEN
    RETURN QUERY SELECT 'mobility'::text, ARRAY['other']::text[], '{}'::text[], NULL::text, true;
    RETURN;
  ELSE
    RETURN QUERY SELECT 'other'::text, ARRAY['other']::text[], '{}'::text[], eq, false;
    RETURN;
  END IF;
  IF p = 'horizontal_pull' AND n ~ 'wide' THEN
    pm := ARRAY['upper_back', 'rear_delts']::text[]; sm := ARRAY['biceps']::text[];
  ELSIF p = 'horizontal_pull' AND n ~ '(lat focus|lat row|kayak|single arm|one arm|1 arm)' THEN
    pm := ARRAY['lats', 'upper_back']::text[]; sm := ARRAY['biceps', 'rear_delts']::text[];
  ELSIF p = 'vertical_pull' AND n ~ '(chin|underhand|supinated)' THEN
    sm := ARRAY['biceps', 'upper_back']::text[];
  ELSIF p = 'squat' AND n ~ '(sumo|wide stance|plie)' THEN
    pm := ARRAY['quads', 'glutes', 'adductors']::text[];
  ELSIF p = 'hinge' AND n ~ '(sumo)' AND n !~ '(romanian|rdl|stiff)' THEN
    pm := ARRAY['glutes', 'quads', 'adductors']::text[]; sm := ARRAY['hamstrings', 'lower_back', 'upper_back', 'forearms']::text[];
  ELSIF p = 'horizontal_press' AND n ~ '(wide grip)' THEN
    pm := ARRAY['chest']::text[]; sm := ARRAY['front_delts', 'triceps']::text[];
  ELSIF p = 'lunge' AND n ~ '(lateral lunge|side lunge|cossack)' THEN
    pm := ARRAY['adductors', 'quads', 'glutes']::text[]; sm := '{}'::text[];
  END IF;
  sm := ARRAY(SELECT m FROM unnest(sm) WITH ORDINALITY AS u(m, o) WHERE m <> ALL (pm) ORDER BY o);
  IF p = 'mobility' AND eq IS DISTINCT FROM 'Bands' THEN eq := NULL; END IF;
  RETURN QUERY SELECT p, pm, sm, eq, true;
END
$fn$;

-- Fine pattern → the coarse vocabulary exercises.primary_movement_pattern allows.
CREATE OR REPLACE FUNCTION public.exercise_coarse_pattern(_pattern text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $fn$
  SELECT CASE _pattern WHEN 'squat' THEN 'squat' WHEN 'lunge' THEN 'squat' WHEN 'hinge' THEN 'hip_hinge' WHEN 'back_extension' THEN 'hip_hinge' WHEN 'knee_extension' THEN 'knee_extension' WHEN 'knee_flexion' THEN 'hamstring_curl' WHEN 'hip_thrust' THEN 'glutes' WHEN 'hip_abduction' THEN 'glutes' WHEN 'hip_adduction' THEN 'other' WHEN 'hip_flexion' THEN 'core' WHEN 'calf_raise' THEN 'other' WHEN 'horizontal_press' THEN 'horizontal_push' WHEN 'incline_press' THEN 'horizontal_push' WHEN 'dip' THEN 'horizontal_push' WHEN 'chest_fly' THEN 'horizontal_push' WHEN 'vertical_press' THEN 'vertical_push' WHEN 'horizontal_pull' THEN 'horizontal_pull' WHEN 'vertical_pull' THEN 'vertical_pull' WHEN 'pullover' THEN 'vertical_pull' WHEN 'shrug' THEN 'other' WHEN 'rear_delt' THEN 'delts' WHEN 'lateral_raise' THEN 'delts' WHEN 'front_raise' THEN 'delts' WHEN 'elbow_flexion' THEN 'arms' WHEN 'elbow_extension' THEN 'arms' WHEN 'wrist' THEN 'arms' WHEN 'core_flexion' THEN 'core' WHEN 'core_anti_extension' THEN 'core' WHEN 'core_rotation' THEN 'core' WHEN 'core_lateral' THEN 'core' WHEN 'carry' THEN 'conditioning' WHEN 'olympic' THEN 'conditioning' WHEN 'plyometric' THEN 'conditioning' WHEN 'conditioning' THEN 'conditioning' WHEN 'mobility' THEN 'other' WHEN 'other' THEN 'other' ELSE NULL END
$fn$;

-- Patterns that never build muscle volume.
CREATE OR REPLACE FUNCTION public.exercise_pattern_counts_toward_volume(_pattern text)
 RETURNS boolean
 LANGUAGE sql
 IMMUTABLE PARALLEL SAFE
 SET search_path TO 'public'
AS $fn$
  SELECT _pattern IS NULL OR _pattern NOT IN ('mobility', 'conditioning')
$fn$;

-- The existing muscle-tag trigger (exercises_muscle_tags) derives tags through
-- exercise_derived_muscles → exercise_muscle_profile. Same signature, new rules.
-- Stretches / cardio / unknown names report "not matched" so the trigger keeps
-- its existing fallback (the label's muscle, else 'other').
CREATE OR REPLACE FUNCTION public.exercise_muscle_profile(_name text, _category text DEFAULT NULL::text)
 RETURNS TABLE(primary_muscles text[], secondary_muscles text[], matched boolean)
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $fn$
  SELECT CASE WHEN ok THEN k.primary_muscles END,
         CASE WHEN ok THEN k.secondary_muscles END,
         ok
    FROM public.exercise_classify(_name, _category) k,
         LATERAL (SELECT k.matched AND public.exercise_pattern_counts_toward_volume(k.pattern) AS ok) x
$fn$;

-- Label guess for a new exercise: the caller's own primary muscle, else the
-- classifier's, else the legacy keyword guess (unknown → "Other" + review flag).
CREATE OR REPLACE FUNCTION public.exercises_autoclassify()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $fn$
DECLARE
  guess text;
  first_key text;
BEGIN
  IF NEW.primary_muscle_group IS NULL OR NEW.primary_muscle_group = '' THEN
    first_key := regexp_replace(lower(btrim(coalesce(NEW.muscle_groups[1], ''))), '[^a-z]+', '_', 'g');
    IF first_key NOT IN ('', 'other') THEN
      guess := public.muscle_label_from_key(first_key);
    END IF;
    IF guess IS NULL THEN
      -- A recognised stretch / cardio drill is "Other" by design, not a gap to review.
      SELECT CASE WHEN public.exercise_pattern_counts_toward_volume(k.pattern)
                  THEN public.muscle_label_from_key(k.primary_muscles[1]) ELSE 'Other' END
        INTO guess
        FROM public.exercise_classify(NEW.name, NEW.category) k WHERE k.matched;
    END IF;
    guess := coalesce(guess, public.classify_exercise_muscle(NEW.name, NEW.muscle_group));
    IF guess IS NOT NULL THEN
      NEW.primary_muscle_group := guess;
      NEW.needs_muscle_review := false;
    ELSE
      NEW.primary_muscle_group := 'Other';
      NEW.needs_muscle_review := true;
    END IF;
  END IF;
  -- Otherwise respect what the caller stored (admin explicitly chose).
  RETURN NEW;
END;
$fn$;

-- Movement pattern, volume flag, equipment and the legacy free-text label for a
-- new exercise, where the caller left them blank. Runs after
-- exercises_muscle_tags_trg (same-timing triggers fire in name order), so the
-- muscle tags are already final here.
CREATE OR REPLACE FUNCTION public.exercises_pattern_volume_defaults()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $fn$
DECLARE
  k record;
BEGIN
  SELECT * INTO k FROM public.exercise_classify(NEW.name, NEW.category);
  IF NEW.primary_movement_pattern IS NULL AND k.matched THEN
    NEW.primary_movement_pattern := public.exercise_coarse_pattern(k.pattern);
  END IF;
  IF btrim(coalesce(NEW.equipment, '')) = '' AND k.equipment IS NOT NULL THEN
    NEW.equipment := k.equipment;
  END IF;
  -- Stretches, cardio and exercises with no known muscle don't build volume.
  IF NOT public.exercise_pattern_counts_toward_volume(k.pattern)
     OR coalesce(NEW.muscle_groups, '{}') IN ('{}'::text[], ARRAY['other']::text[]) THEN
    NEW.counts_toward_volume := false;
  END IF;
  IF btrim(coalesce(NEW.muscle_group, '')) = '' THEN
    NEW.muscle_group := nullif((
      SELECT string_agg(public.muscle_label_from_key(m), ', ' ORDER BY o)
        FROM unnest(NEW.muscle_groups) WITH ORDINALITY AS u(m, o)
       WHERE m <> 'other'), '');
  END IF;
  RETURN NEW;
END;
$fn$;

DROP TRIGGER IF EXISTS exercises_pattern_volume_trg ON public.exercises;
CREATE TRIGGER exercises_pattern_volume_trg
  BEFORE INSERT ON public.exercises
  FOR EACH ROW EXECUTE FUNCTION public.exercises_pattern_volume_defaults();
