-- Canonical exercise cleanup: remap-before-delete, history preserving.
-- Scope is intentionally conservative: only role-prefixed records whose stripped
-- name exactly matches an existing active canonical exercise are auto-merged.

CREATE OR REPLACE FUNCTION public.exercise_identity_name(value text)
RETURNS text
LANGUAGE sql IMMUTABLE
SET search_path = public
AS $$
  SELECT trim(regexp_replace(
    lower(regexp_replace(
      regexp_replace(coalesce(value, ''),
        '^\\s*(primary|secondary|tertiary|quaternary|quinary|limiter|accessory|isolation|gpp)(\\s+(squat|bench(\\s+press)?|deadlift))?\\s*[-—–:|]+\\s*',
        '', 'i'),
      '[^a-z0-9]+', ' ', 'g')),
    '\\s+', ' ', 'g'));
$$;

CREATE TABLE IF NOT EXISTS public.exercise_dedupe_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  duplicate_id uuid NOT NULL,
  canonical_id uuid NOT NULL,
  duplicate_name text NOT NULL,
  canonical_name text NOT NULL,
  remapped_at timestamptz NOT NULL DEFAULT now()
);

DO $cleanup$
DECLARE
  d record;
  remaining bigint;
BEGIN
  FOR d IN
    SELECT dup.id AS duplicate_id, can.id AS canonical_id,
           dup.name AS duplicate_name, can.name AS canonical_name
    FROM public.exercises dup
    JOIN public.exercises can
      ON can.id <> dup.id
     AND coalesce(can.archived, false) = false
     AND public.exercise_identity_name(can.name) = public.exercise_identity_name(dup.name)
     AND lower(can.name) = public.exercise_identity_name(can.name)
    WHERE coalesce(dup.archived, false) = false
      AND dup.name ~* '^\\s*(primary|secondary|tertiary|quaternary|quinary|limiter|accessory|isolation|gpp)(\\s+(squat|bench(\\s+press)?|deadlift))?\\s*[-—–:|]+'
  LOOP
    -- Remap every known direct FK. Program-row IDs stay unchanged, so
    -- pl_row_results/completed-set history keeps the exact historical prescription.
    UPDATE public.pl_exercise_rows SET exercise_id = d.canonical_id WHERE exercise_id = d.duplicate_id;
    UPDATE public.member_set_logs SET exercise_id = d.canonical_id WHERE exercise_id = d.duplicate_id;
    UPDATE public.pl_client_maxes SET exercise_id = d.canonical_id WHERE exercise_id = d.duplicate_id;
    UPDATE public.pl_exercise_notes SET exercise_id = d.canonical_id WHERE exercise_id = d.duplicate_id;
    UPDATE public.member_exercise_notes SET exercise_id = d.canonical_id WHERE exercise_id = d.duplicate_id;
    UPDATE public.member_exercise_swaps SET exercise_id = d.canonical_id WHERE exercise_id = d.duplicate_id;
    UPDATE public.warmup_assignments SET exercise_id = d.canonical_id WHERE exercise_id = d.duplicate_id;

    -- Fail closed: delete only after all known required references are zero.
    SELECT
      (SELECT count(*) FROM public.pl_exercise_rows WHERE exercise_id=d.duplicate_id) +
      (SELECT count(*) FROM public.member_set_logs WHERE exercise_id=d.duplicate_id) +
      (SELECT count(*) FROM public.pl_client_maxes WHERE exercise_id=d.duplicate_id) +
      (SELECT count(*) FROM public.pl_exercise_notes WHERE exercise_id=d.duplicate_id) +
      (SELECT count(*) FROM public.member_exercise_notes WHERE exercise_id=d.duplicate_id) +
      (SELECT count(*) FROM public.member_exercise_swaps WHERE exercise_id=d.duplicate_id) +
      (SELECT count(*) FROM public.warmup_assignments WHERE exercise_id=d.duplicate_id)
    INTO remaining;

    IF remaining = 0 THEN
      INSERT INTO public.exercise_dedupe_audit(duplicate_id,canonical_id,duplicate_name,canonical_name)
      VALUES(d.duplicate_id,d.canonical_id,d.duplicate_name,d.canonical_name);
      DELETE FROM public.exercises WHERE id=d.duplicate_id;
    END IF;
  END LOOP;
END
$cleanup$;

-- Database backstop. App/AI builders should reuse the existing ID; this guard
-- prevents a missed code path from silently recreating the same exercise under
-- a programming-role prefix.
CREATE OR REPLACE FUNCTION public.prevent_duplicate_exercise_identity()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE existing_id uuid;
BEGIN
  SELECT id INTO existing_id
  FROM public.exercises
  WHERE id IS DISTINCT FROM NEW.id
    AND coalesce(archived,false)=false
    AND public.exercise_identity_name(name)=public.exercise_identity_name(NEW.name)
  ORDER BY
    CASE WHEN lower(name)=public.exercise_identity_name(name) THEN 0 ELSE 1 END,
    created_at ASC NULLS LAST
  LIMIT 1;
  IF existing_id IS NOT NULL THEN
    RAISE EXCEPTION 'Exercise already exists as canonical id %; reuse the existing exercise instead of creating a duplicate.', existing_id
      USING ERRCODE='23505';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS exercises_prevent_duplicate_identity ON public.exercises;
CREATE TRIGGER exercises_prevent_duplicate_identity
BEFORE INSERT OR UPDATE OF name, archived ON public.exercises
FOR EACH ROW EXECUTE FUNCTION public.prevent_duplicate_exercise_identity();
